//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel, UIView;

@interface AboutViewController : UIViewController
{
    UILabel *_versiobLabel;
    UIView *_rankView;
    UIView *_lisenceView;
}

@property(nonatomic) __weak UIView *lisenceView; // @synthesize lisenceView=_lisenceView;
@property(nonatomic) __weak UIView *rankView; // @synthesize rankView=_rankView;
@property(nonatomic) __weak UILabel *versiobLabel; // @synthesize versiobLabel=_versiobLabel;
- (void).cxx_destruct;
- (void)actionGotoLisence;
- (void)actionGotoRank;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

