//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSString;

@interface AddUserFavoriteOp : BaseOp
{
    NSString *_req_title;
    NSString *_req_subtitle;
    NSString *_req_url;
    NSString *_req_thumbnail;
}

@property(copy, nonatomic) NSString *req_thumbnail; // @synthesize req_thumbnail=_req_thumbnail;
@property(copy, nonatomic) NSString *req_url; // @synthesize req_url=_req_url;
@property(copy, nonatomic) NSString *req_subtitle; // @synthesize req_subtitle=_req_subtitle;
@property(copy, nonatomic) NSString *req_title; // @synthesize req_title=_req_title;
- (void).cxx_destruct;
- (id)rac_postRequest;

@end

