//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKTokenPool, JXUserInfo, MainTabBarVC, UINavigationController, VcodeLoginViewController;

@interface AppManager : NSObject
{
    _Bool _hasNewMsg;
    MainTabBarVC *_mainTabbarVC;
    VcodeLoginViewController *_loginVC;
    UINavigationController *_curNavCtrl;
    JXUserInfo *_userInfo;
    HKTokenPool *_tokenPool;
}

+ (id)sharedManager;
@property(readonly, nonatomic) HKTokenPool *tokenPool; // @synthesize tokenPool=_tokenPool;
@property(nonatomic) _Bool hasNewMsg; // @synthesize hasNewMsg=_hasNewMsg;
@property(retain, nonatomic) JXUserInfo *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) __weak UINavigationController *curNavCtrl; // @synthesize curNavCtrl=_curNavCtrl;
@property(nonatomic) __weak VcodeLoginViewController *loginVC; // @synthesize loginVC=_loginVC;
@property(nonatomic) __weak MainTabBarVC *mainTabbarVC; // @synthesize mainTabbarVC=_mainTabbarVC;
- (void).cxx_destruct;
- (void)resetWithWechat;
- (void)resetWithAccount:(id)arg1;
- (id)init;

@end

