//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIButton, UITextField;

@interface BankCardAuthViewController : UIViewController
{
    UITextField *_nameTextFiled;
    UITextField *_idTextField;
    UITextField *_bankCardNoTextField;
    UITextField *_phoneTextField;
    UIButton *_authBtn;
}

@property(nonatomic) __weak UIButton *authBtn; // @synthesize authBtn=_authBtn;
@property(nonatomic) __weak UITextField *phoneTextField; // @synthesize phoneTextField=_phoneTextField;
@property(nonatomic) __weak UITextField *bankCardNoTextField; // @synthesize bankCardNoTextField=_bankCardNoTextField;
@property(nonatomic) __weak UITextField *idTextField; // @synthesize idTextField=_idTextField;
@property(nonatomic) __weak UITextField *nameTextFiled; // @synthesize nameTextFiled=_nameTextFiled;
- (void).cxx_destruct;
- (void)getBankCardAuthInfo;
- (void)actionBankCardAuth;
- (void)actionBack;
- (void)setupNavigationBar;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

