//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSString;

@interface BankCardVerifyOp : BaseOp
{
    NSString *_name;
    NSString *_idNo;
    NSString *_mobile;
    NSString *_bankCode;
}

@property(copy, nonatomic) NSString *bankCode; // @synthesize bankCode=_bankCode;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString *idNo; // @synthesize idNo=_idNo;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

