//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, RACSignal;

@protocol BaseOpDelegate <NSObject>

@optional
- (id)returnSimulateResponse;
- (id)parseResponseObject:(id)arg1;
- (_Bool)shouldHandleDefaultError;
- (NSError *)mapError:(NSError *)arg1;
- (RACSignal *)rac_getRequest;
- (RACSignal *)rac_postRequest;
@end

