//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSArray, NSString;

@interface BonusGetOp : BaseOp
{
    NSString *_searchTime;
    long long _pageNo;
    long long _pageSize;
    long long _rsp_totalBonus;
    long long _rsp_totalPercent;
    NSArray *_rsp_bonusList;
}

@property(retain, nonatomic) NSArray *rsp_bonusList; // @synthesize rsp_bonusList=_rsp_bonusList;
@property(nonatomic) long long rsp_totalPercent; // @synthesize rsp_totalPercent=_rsp_totalPercent;
@property(nonatomic) long long rsp_totalBonus; // @synthesize rsp_totalBonus=_rsp_totalBonus;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long pageNo; // @synthesize pageNo=_pageNo;
@property(retain, nonatomic) NSString *searchTime; // @synthesize searchTime=_searchTime;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

