//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSString;

@interface CheckVersionOp : BaseOp
{
    _Bool _rsp_force;
    NSString *_version;
    NSString *_os;
    NSString *_rsp_version;
    NSString *_rsp_url;
    NSString *_rsp_updateInfo;
}

@property(copy, nonatomic) NSString *rsp_updateInfo; // @synthesize rsp_updateInfo=_rsp_updateInfo;
@property(nonatomic) _Bool rsp_force; // @synthesize rsp_force=_rsp_force;
@property(copy, nonatomic) NSString *rsp_url; // @synthesize rsp_url=_rsp_url;
@property(copy, nonatomic) NSString *rsp_version; // @synthesize rsp_version=_rsp_version;
@property(copy, nonatomic) NSString *os; // @synthesize os=_os;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

