//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CKBaseStore : NSObject
{
}

+ (id)fetchOrCreateStore;
+ (id)fetchExistsStore;
+ (id)fetchOrCreateStoreForKey:(id)arg1;
+ (id)fetchExistsStoreForKey:(id)arg1;
+ (id)storeTable;

@end

