//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CKItemDelegate.h"

@class NSMutableDictionary, NSString;

@interface CKDict : NSObject <CKItemDelegate>
{
    _Bool _forceReload;
    NSMutableDictionary *_dict;
}

+ (id)dictWith:(id)arg1;
+ (id)dictWithCKDict:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *dict; // @synthesize dict=_dict;
@property(nonatomic) _Bool forceReload; // @synthesize forceReload=_forceReload;
- (void).cxx_destruct;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)setKey:(id)arg1;
- (id)key;
- (id)initWithDict:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

