//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, RACSignal;

@interface CKEventPromise : NSObject
{
    _Bool _shouldIgnoreError;
    RACSignal *_eventSignal;
    NSString *_eventName;
    id _eventObject;
    NSDictionary *_eventUserInfo;
    double _delayInterval;
}

@property(nonatomic) _Bool shouldIgnoreError; // @synthesize shouldIgnoreError=_shouldIgnoreError;
@property(nonatomic) double delayInterval; // @synthesize delayInterval=_delayInterval;
@property(retain, nonatomic) NSDictionary *eventUserInfo; // @synthesize eventUserInfo=_eventUserInfo;
@property(retain, nonatomic) id eventObject; // @synthesize eventObject=_eventObject;
@property(retain, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
@property(retain, nonatomic) RACSignal *eventSignal; // @synthesize eventSignal=_eventSignal;
- (void).cxx_destruct;
- (id)send;
- (id)setUserInfo:(id)arg1;
- (id)setObject:(id)arg1;
- (id)mapSignal:(CDUnknownBlockType)arg1;
- (id)ignoreError;
- (id)delay:(double)arg1;

@end

