//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, RACSignal;

@interface CKEvent : NSObject
{
    RACSignal *_signal;
    NSString *_name;
    id _object;
    NSDictionary *_userInfo;
}

+ (id)eventWithName:(id)arg1 object:(id)arg2 userInfo:(id)arg3 signal:(id)arg4;
+ (id)eventWithName:(id)arg1 object:(id)arg2 signal:(id)arg3;
+ (id)eventWithName:(id)arg1 signal:(id)arg2;
@property(readonly, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(readonly, nonatomic) id object; // @synthesize object=_object;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) RACSignal *signal; // @synthesize signal=_signal;
- (void).cxx_destruct;
- (_Bool)isEqualForName:(id)arg1;
- (_Bool)isEqualForAnyoneOfNames:(id)arg1;
- (id)setUserInfo:(id)arg1;
- (id)setObject:(id)arg1;
- (id)sendWithIgnoreError:(_Bool)arg1 andDelay:(double)arg2;
- (id)sendAndIgnoreError;
- (id)send;
- (id)mapSignal:(CDUnknownBlockType)arg1;
- (id)initWithName:(id)arg1 object:(id)arg2 userInfo:(id)arg3 signal:(id)arg4;

@end

