//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKQueue.h"

#import "CKItemDelegate.h"

@class NSString;

@interface CKList : CKQueue <CKItemDelegate>
{
    id _key;
}

+ (id)listWithArray:(id)arg1;
+ (id)list;
- (void).cxx_destruct;
- (void)addObjectsFromArray:(id)arg1;
- (void)insertObject:(id)arg1 withKey:(id)arg2 atIndex:(long long)arg3;
- (void)replaceObject:(id)arg1 withKey:(id)arg2 atIndex:(long long)arg3;
- (void)addObject:(id)arg1 forKey:(id)arg2;
- (id)setKey:(id)arg1;
- (id)key;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

