//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CKMap : NSObject
{
    NSMutableDictionary *_mDict;
}

@property(retain, nonatomic) NSMutableDictionary *mDict; // @synthesize mDict=_mDict;
- (void).cxx_destruct;
- (void)removeAllObjects;
- (id)allObjects;
- (id)allKeys;
- (id)objectsForKey:(id)arg1;
- (void)addObject:(id)arg1 forKey:(id)arg2;
- (void)addObjects:(id)arg1 forKey:(id)arg2;

@end

