//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CKObjectHolder : NSObject
{
    id _object;
    long long _count;
}

+ (id)holderWithObject:(id)arg1;
@property(readonly, nonatomic) long long count; // @synthesize count=_count;
@property(readonly, nonatomic) id object; // @synthesize object=_object;
- (void).cxx_destruct;
- (_Bool)decreaseCount;
- (void)increaseCount;

@end

