//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSNumber;

@interface CKQueue : NSObject
{
    NSNumber *_queueid;
    NSMutableDictionary *_cache;
    NSMutableArray *_array;
}

+ (id)queueWithCache:(id)arg1;
+ (id)queue;
@property(retain, nonatomic) NSMutableArray *array; // @synthesize array=_array;
@property(retain, nonatomic) NSMutableDictionary *cache; // @synthesize cache=_cache;
@property(readonly, nonatomic) NSNumber *queueid; // @synthesize queueid=_queueid;
- (void).cxx_destruct;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)createQueueNode;
- (id)allObjects;
- (unsigned long long)count;
- (unsigned long long)indexOfObjectForKey:(id)arg1;
- (id)objectsInRange:(struct _NSRange)arg1;
- (id)objectsFromIndex:(unsigned long long)arg1;
- (id)objectForKey:(id)arg1;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)keyForObjectAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 withKey:(id)arg2 atIndex:(long long)arg3;
- (void)replaceObject:(id)arg1 withKey:(id)arg2 atIndex:(long long)arg3;
- (void)replaceObject:(id)arg1 forKey:(id)arg2;
- (void)removeAllObjects;
- (void)removeObjectsInRange:(struct _NSRange)arg1;
- (void)removeObjectsFromIndex:(unsigned long long)arg1;
- (void)removeObjectAtIndex:(unsigned long long)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)addObjectsAndKeys:(id)arg1;
- (void)addObjectsFromQueue:(id)arg1;
- (void)addObject:(id)arg1 forKey:(id)arg2;
- (id)initWithCache:(id)arg1;

@end

