//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface CKQueueNode : NSObject
{
    id _object;
    NSNumber *_queueid;
    id _key;
}

@property(retain, nonatomic) id key; // @synthesize key=_key;
@property(retain, nonatomic) NSNumber *queueid; // @synthesize queueid=_queueid;
@property(retain, nonatomic) id object; // @synthesize object=_object;
- (void).cxx_destruct;

@end

