//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CKSegmentHelper : NSObject
{
    NSMutableDictionary *_itemGroups;
}

@property(retain, nonatomic) NSMutableDictionary *itemGroups; // @synthesize itemGroups=_itemGroups;
- (void).cxx_destruct;
- (id)itemGroupForName:(id)arg1;
- (void)changeItemState:(id)arg1 withSelected:(_Bool)arg2;
- (_Bool)isItemSelected:(id)arg1;
- (void)setComplete:(CDUnknownBlockType)arg1 forGroupName:(id)arg2;
- (void)cleanItem:(id)arg1;
- (void)removeItem:(id)arg1 forGroupName:(id)arg2;
- (void)removeAllItemsForGroupName:(id)arg1;
- (void)removeAllItemGroups;
- (id)itemsForGroupName:(id)arg1;
- (void)selectItem:(id)arg1 forGroupName:(id)arg2;
- (void)cancelSelectedForGroupName:(id)arg1;
- (void)selectItem:(id)arg1;
- (void)addItem:(id)arg1 forGroupName:(id)arg2 withChangedBlock:(CDUnknownBlockType)arg3;
- (void)addItems:(id)arg1 forGroupName:(id)arg2 withChangedBlock:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)init;

@end

