//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage, UIImageView;

@interface CKShadowView : UIView
{
    UIImage *_shadowImage;
    UIView *_contentView;
    UIImageView *_mImageView;
    struct UIEdgeInsets _shadowInsets;
}

@property(retain, nonatomic) UIImageView *mImageView; // @synthesize mImageView=_mImageView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIImage *shadowImage; // @synthesize shadowImage=_shadowImage;
@property(nonatomic) struct UIEdgeInsets shadowInsets; // @synthesize shadowInsets=_shadowInsets;
- (void).cxx_destruct;
- (void)setBackgroundColor:(id)arg1;
- (struct CGRect)_newRectFrom:(struct CGRect)arg1 forInsets:(struct UIEdgeInsets)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (void)commInitWithFrame:(struct CGRect)arg1;
- (id)initWithShadowImage:(id)arg1 shadowInsets:(struct UIEdgeInsets)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

