//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKEvent, NSArray, NSString, RACSignal;

@protocol CKStoreDelegate <NSObject>
+ (id)fetchOrCreateStore;
+ (id)fetchExistsStore;
- (RACSignal *)rac_subscribeWithTarget:(id)arg1 domain:(NSString *)arg2;
- (RACSignal *)rac_subscribeWithTarget:(id)arg1 domainList:(NSArray *)arg2;
- (void)subscribeWithTarget:(id)arg1 domainList:(NSArray *)arg2 receiver:(void (^)(id, CKEvent *))arg3;
- (void)subscribeWithTarget:(id)arg1 domain:(NSString *)arg2 receiver:(void (^)(id, CKEvent *))arg3;
- (void)triggerEvent:(CKEvent *)arg1 forDomainList:(NSArray *)arg2;
- (void)triggerEvent:(CKEvent *)arg1 forDomain:(NSString *)arg2;
- (void)triggerEvent:(CKEvent *)arg1;
- (CKEvent *)inlineEvent:(CKEvent *)arg1 handler:(void (^)(CKEvent *))arg2;
- (CKEvent *)inlineEvent:(CKEvent *)arg1 forDomainList:(NSArray *)arg2;
- (CKEvent *)inlineEvent:(CKEvent *)arg1 forDomain:(NSString *)arg2;
- (CKEvent *)inlineEvent:(CKEvent *)arg1;
@end

