//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CKStoreDelegate.h"

@class NSMapTable, NSMutableDictionary, NSString;

@interface CKStore : NSObject <CKStoreDelegate>
{
    NSMapTable *_weakTable;
    NSMutableDictionary *_eventDict;
}

+ (id)fetchOrCreateStore;
+ (id)fetchExistsStore;
+ (id)fetchOrCreateStoreForWeakKey:(id)arg1;
+ (id)fetchExistsStoreForWeakKey:(id)arg1;
+ (id)storeTable;
@property(retain, nonatomic) NSMutableDictionary *eventDict; // @synthesize eventDict=_eventDict;
@property(retain, nonatomic) NSMapTable *weakTable; // @synthesize weakTable=_weakTable;
- (void).cxx_destruct;
- (id)rac_subscribeWithTarget:(id)arg1 domain:(id)arg2;
- (id)rac_subscribeWithTarget:(id)arg1 domainList:(id)arg2;
- (void)subscribeWithTarget:(id)arg1 domain:(id)arg2 receiver:(CDUnknownBlockType)arg3;
- (void)subscribeWithTarget:(id)arg1 domainList:(id)arg2 receiver:(CDUnknownBlockType)arg3;
- (void)triggerEvent:(id)arg1 forDomainList:(id)arg2;
- (void)triggerEvent:(id)arg1 forDomain:(id)arg2;
- (void)triggerEvent:(id)arg1;
- (id)inlineEvent:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)inlineEvent:(id)arg1 forDomainList:(id)arg2;
- (id)inlineEvent:(id)arg1 forDomain:(id)arg2;
- (id)inlineEvent:(id)arg1;
- (void)observeEventForName:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)observeEventForName:(id)arg1 selector:(SEL)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

