//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSValue;

@interface CKWeakHolder : NSObject
{
    NSValue *_mValue;
}

+ (id)holderWithObject:(id)arg1;
@property(retain, nonatomic) NSValue *mValue; // @synthesize mValue=_mValue;
- (void).cxx_destruct;
- (void)dealloc;
- (id)holdedObject;
- (id)initWithObject:(id)arg1;

@end

