//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CustomDictionary : NSObject
{
    NSMutableDictionary *_mMutableDictionary;
}

@property(retain, nonatomic) NSMutableDictionary *mMutableDictionary; // @synthesize mMutableDictionary=_mMutableDictionary;
- (void).cxx_destruct;
- (void)removeObserver:(id)arg1;
- (void)removeObserverForKey:(id)arg1;
- (void)removeAllObservers;
- (id)observerForKey:(id)arg1;
- (void)setObserver:(id)arg1 forKey:(id)arg2;
- (void)dealloc;
- (id)init;

@end

