//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSString;

@interface FeedbackAddOp : BaseOp
{
    NSString *_title;
    NSString *_content;
    NSString *_thumbnail;
    NSString *_insurer;
    NSString *_policyNo;
}

@property(copy, nonatomic) NSString *policyNo; // @synthesize policyNo=_policyNo;
@property(copy, nonatomic) NSString *insurer; // @synthesize insurer=_insurer;
@property(copy, nonatomic) NSString *thumbnail; // @synthesize thumbnail=_thumbnail;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)rac_postRequest;

@end

