//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSArray;

@interface FeedbackListGetOp : BaseOp
{
    NSArray *_rsp_feedbackArray;
}

@property(retain, nonatomic) NSArray *rsp_feedbackArray; // @synthesize rsp_feedbackArray=_rsp_feedbackArray;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

