//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FeedbackModel : NSObject
{
    NSString *_feedbackTime;
    long long _feedbackStatus;
    NSString *_title;
    NSString *_insurer;
    NSString *_policyNo;
    NSString *_thumbnail;
    NSString *_content;
}

@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *thumbnail; // @synthesize thumbnail=_thumbnail;
@property(retain, nonatomic) NSString *policyNo; // @synthesize policyNo=_policyNo;
@property(retain, nonatomic) NSString *insurer; // @synthesize insurer=_insurer;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long feedbackStatus; // @synthesize feedbackStatus=_feedbackStatus;
@property(retain, nonatomic) NSString *feedbackTime; // @synthesize feedbackTime=_feedbackTime;
- (void).cxx_destruct;

@end

