//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSArray;

@interface GetNewsTypeOp : BaseOp
{
    NSArray *_rsp_newsTypeArray;
}

@property(retain, nonatomic) NSArray *rsp_newsTypeArray; // @synthesize rsp_newsTypeArray=_rsp_newsTypeArray;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

