//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSArray, NSNumber;

@interface GetNewsOp : BaseOp
{
    long long _pageNo;
    long long _pageSize;
    NSNumber *_type;
    NSArray *_rsp_newsArray;
}

@property(retain, nonatomic) NSArray *rsp_newsArray; // @synthesize rsp_newsArray=_rsp_newsArray;
@property(retain, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long pageNo; // @synthesize pageNo=_pageNo;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

