//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSString;

@interface GetTokenByWechatCodeOp : BaseOp
{
    _Bool _bindFlag;
    NSString *_req_wxCode;
    NSString *_rsp_expires;
    NSString *_rsp_token;
}

@property(nonatomic) _Bool bindFlag; // @synthesize bindFlag=_bindFlag;
@property(retain, nonatomic) NSString *rsp_token; // @synthesize rsp_token=_rsp_token;
@property(retain, nonatomic) NSString *rsp_expires; // @synthesize rsp_expires=_rsp_expires;
@property(retain, nonatomic) NSString *req_wxCode; // @synthesize req_wxCode=_req_wxCode;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

