//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSString;

@interface GetTokenOp : BaseOp
{
    NSString *_req_phone;
    NSString *_rsp_expires;
    NSString *_rsp_token;
}

@property(retain, nonatomic) NSString *rsp_token; // @synthesize rsp_token=_rsp_token;
@property(retain, nonatomic) NSString *rsp_expires; // @synthesize rsp_expires=_rsp_expires;
@property(copy, nonatomic) NSString *req_phone; // @synthesize req_phone=_req_phone;
- (void).cxx_destruct;
- (id)description;
- (id)returnSimulateResponse;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

