//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class JXUserInfo;

@interface GetUserInfoOp : BaseOp
{
    JXUserInfo *_rsp_userInfo;
}

@property(retain, nonatomic) JXUserInfo *rsp_userInfo; // @synthesize rsp_userInfo=_rsp_userInfo;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

