//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class RACSubject, UIImage, UIImageView;

@interface HKImageShowingViewController : UIViewController
{
    UIImage *_image;
    UIImageView *_imageView;
    RACSubject *_subject;
}

@property(retain, nonatomic) RACSubject *subject; // @synthesize subject=_subject;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)actionFinish:(id)arg1;
- (void)actionCancel:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithSubject:(id)arg1;

@end

