//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSString, UINavigationController;

@interface HKImagePicker : NSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    _Bool _shouldShowBigImage;
    _Bool _allowsEditing;
    _Bool _shouldCompress;
    UINavigationController *_imgPickerNavCtrl;
    struct CGSize _compressedSize;
}

+ (id)imagePicker;
@property(nonatomic) __weak UINavigationController *imgPickerNavCtrl; // @synthesize imgPickerNavCtrl=_imgPickerNavCtrl;
@property(nonatomic) struct CGSize compressedSize; // @synthesize compressedSize=_compressedSize;
@property(nonatomic) _Bool shouldCompress; // @synthesize shouldCompress=_shouldCompress;
@property(nonatomic) _Bool allowsEditing; // @synthesize allowsEditing=_allowsEditing;
@property(nonatomic) _Bool shouldShowBigImage; // @synthesize shouldShowBigImage=_shouldShowBigImage;
- (void).cxx_destruct;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (id)rac_pickPhotoTargetVC:(id)arg1 inView:(id)arg2;
- (id)rac_pickImageInTargetVC:(id)arg1 inView:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

