//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HKLoginModel : NSObject
{
}

+ (void)cleanPwdForAccount:(id)arg1;
+ (void)logout;
+ (void)logoutWithoutNetworking;
+ (void)saveSkey:(id)arg1 forAccount:(id)arg2 loginType:(long long)arg3;
+ (id)rac_saveSkey:(id)arg1 forAccount:(id)arg2 loginType:(long long)arg3;
+ (id)getSkeyForAccount:(id)arg1 loginType:(long long)arg2;
+ (id)rac_getSkeyForAccount:(id)arg1 loginType:(long long)arg2;
+ (id)globalRetrySignal;
+ (_Bool)hasPasswordForAccount:(id)arg1;
+ (void)saveNearlyLoginInfoWithAccount:(id)arg1 type:(long long)arg2 token:(id)arg3;
+ (id)nearlyLoginAccount;
+ (id)nearlyLoginInfo;
- (id)rac_commonValidateTokenOp:(id)arg1 account:(id)arg2 token:(id)arg3;
- (id)rac_getTokenWithAccount:(id)arg1;
- (id)skeyFromPassword:(id)arg1;
- (id)rac_retryLogin;
- (id)rac_retryLoginFastWithOldToken:(id)arg1;
- (id)rac_autoLoginWithoutNetworking;
- (id)rac_bindPhoneFromWX:(id)arg1;
- (id)rac_loginByWXCode:(id)arg1;
- (id)rac_loginWithAccount:(id)arg1 validCode:(id)arg2;

@end

