//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HooDatePicker, NSDate, UIButton;

@protocol HooDatePickerDelegate <NSObject>

@optional
- (void)datePicker:(HooDatePicker *)arg1 didClickOther:(UIButton *)arg2;
- (void)datePicker:(HooDatePicker *)arg1 didSelectedDate:(NSDate *)arg2;
- (void)datePicker:(HooDatePicker *)arg1 didCancel:(UIButton *)arg2;
- (void)datePicker:(HooDatePicker *)arg1 dateDidChange:(NSDate *)arg2;
@end

