//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIFont, UIImageView, UILabel;

@interface JTImageBadge : UIView
{
    _Bool _highlighted;
    UILabel *_textLabel;
    UIImageView *_backgroundView;
    NSString *_text;
    UIFont *_textFont;
    double _cornerRadius;
    struct UIEdgeInsets _textInsets;
}

+ (id)badgeWithText:(id)arg1;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) struct UIEdgeInsets textInsets; // @synthesize textInsets=_textInsets;
@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)refreshViewByText:(id)arg1 font:(id)arg2;
- (id)initWithText:(id)arg1 font:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

