//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JXBonusModel : NSObject
{
    NSString *_time;
    NSString *_reason;
    NSString *_bonus;
}

@property(retain, nonatomic) NSString *bonus; // @synthesize bonus=_bonus;
@property(retain, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
- (void).cxx_destruct;

@end

