//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JXMessageModel : NSObject
{
    _Bool _readFlag;
    long long _id;
    NSString *_msgSendTime;
    NSString *_title;
    NSString *_content;
}

@property(nonatomic) _Bool readFlag; // @synthesize readFlag=_readFlag;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *msgSendTime; // @synthesize msgSendTime=_msgSendTime;
@property(nonatomic) long long id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

