//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JXNewsModel : NSObject
{
    long long _id;
    NSString *_title;
    NSString *_thumbnail;
    NSString *_newsUrl;
    NSString *_subtitle;
}

@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *newsUrl; // @synthesize newsUrl=_newsUrl;
@property(copy, nonatomic) NSString *thumbnail; // @synthesize thumbnail=_thumbnail;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

