//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface JXOrderInfoModel : NSObject
{
    NSString *_orderCode;
    NSString *_orderType;
    NSString *_productName;
    NSString *_protectionPlan;
    NSString *_insurer;
    NSString *_insureTime;
    NSString *_payType;
    unsigned long long _payCycle;
    unsigned long long _orderStatus;
    long long _orderAmount;
    NSString *_insuranceCompany;
    NSString *_createTime;
    NSString *_bonus;
    NSArray *_insuranceDetail;
}

@property(retain, nonatomic) NSArray *insuranceDetail; // @synthesize insuranceDetail=_insuranceDetail;
@property(retain, nonatomic) NSString *bonus; // @synthesize bonus=_bonus;
@property(retain, nonatomic) NSString *createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) NSString *insuranceCompany; // @synthesize insuranceCompany=_insuranceCompany;
@property(nonatomic) long long orderAmount; // @synthesize orderAmount=_orderAmount;
@property(nonatomic) unsigned long long orderStatus; // @synthesize orderStatus=_orderStatus;
@property(nonatomic) unsigned long long payCycle; // @synthesize payCycle=_payCycle;
@property(retain, nonatomic) NSString *payType; // @synthesize payType=_payType;
@property(retain, nonatomic) NSString *insureTime; // @synthesize insureTime=_insureTime;
@property(retain, nonatomic) NSString *insurer; // @synthesize insurer=_insurer;
@property(retain, nonatomic) NSString *protectionPlan; // @synthesize protectionPlan=_protectionPlan;
@property(retain, nonatomic) NSString *productName; // @synthesize productName=_productName;
@property(retain, nonatomic) NSString *orderType; // @synthesize orderType=_orderType;
@property(retain, nonatomic) NSString *orderCode; // @synthesize orderCode=_orderCode;
- (void).cxx_destruct;

@end

