//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JXPolicyInfoModel : NSObject
{
    NSString *_policyNo;
    NSString *_insured;
    NSString *_beneficiary;
}

@property(retain, nonatomic) NSString *beneficiary; // @synthesize beneficiary=_beneficiary;
@property(retain, nonatomic) NSString *insured; // @synthesize insured=_insured;
@property(retain, nonatomic) NSString *policyNo; // @synthesize policyNo=_policyNo;
- (void).cxx_destruct;

@end

