//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@class UIView;

@interface JXTableView : UITableView
{
    _Bool _showBottomLoadingView;
    UIView *_bottomLoadingView;
}

@property(nonatomic) _Bool showBottomLoadingView; // @synthesize showBottomLoadingView=_showBottomLoadingView;
@property(retain, nonatomic) UIView *bottomLoadingView; // @synthesize bottomLoadingView=_bottomLoadingView;
- (void).cxx_destruct;
- (_Bool)touchesShouldCancelInContentView:(id)arg1;

@end

