//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface JXToast : UIView
{
    UIView *_targetView;
}

+ (id)sharedToast;
@property(retain, nonatomic) UIView *targetView; // @synthesize targetView=_targetView;
- (void).cxx_destruct;
- (double)displayDurationForString:(id)arg1;
- (id)hudKey;
- (void)dismiss;
- (void)dismissInView:(id)arg1;
- (void)showingWithText:(id)arg1 inView:(id)arg2;
- (void)showText:(id)arg1 inView:(id)arg2;
- (void)showText:(id)arg1;
- (void)showError:(id)arg1 inView:(id)arg2;
- (void)showMistake:(id)arg1;
- (void)showError:(id)arg1;
- (void)showSuccess:(id)arg1;
- (void)showingWithText:(id)arg1;
- (void)showingWithoutText;

@end

