//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface JXUserInfo : NSObject
{
    long long _userId;
    NSString *_phone;
    NSString *_avatar;
    NSString *_sign;
    NSString *_nickName;
    NSString *_name;
    NSString *_email;
    NSDate *_regTime;
    long long _verifyStatus;
    NSString *_openId;
}

@property(copy, nonatomic) NSString *openId; // @synthesize openId=_openId;
@property(nonatomic) long long verifyStatus; // @synthesize verifyStatus=_verifyStatus;
@property(retain, nonatomic) NSDate *regTime; // @synthesize regTime=_regTime;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *sign; // @synthesize sign=_sign;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(nonatomic) long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;

@end

