//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKLoginModel, UIViewController;

@interface LoginViewModel : NSObject
{
    HKLoginModel *_loginModel;
    UIViewController *_originVC;
}

+ (_Bool)loginIfNeededForTargetViewController:(id)arg1 originVC:(id)arg2 withLoginSuccessAction:(CDUnknownBlockType)arg3;
+ (_Bool)forceLoginForTargetViewController:(id)arg1 originVC:(id)arg2 withLoginSuccessAction:(CDUnknownBlockType)arg3;
+ (_Bool)loginIfNeededForTargetViewController:(id)arg1 withLoginSuccessAction:(CDUnknownBlockType)arg2;
+ (_Bool)loginIfNeededForTargetViewController:(id)arg1;
@property(nonatomic) __weak UIViewController *originVC; // @synthesize originVC=_originVC;
@property(retain, nonatomic) HKLoginModel *loginModel; // @synthesize loginModel=_loginModel;
- (void).cxx_destruct;
- (void)dismissForTargetVC:(id)arg1 forSucces:(_Bool)arg2;
- (id)init;

@end

