//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

#import "UITabBarControllerDelegate.h"

@class JTImageBadge, NSString;

@interface MainTabBarVC : UITabBarController <UITabBarControllerDelegate>
{
    JTImageBadge *_mineDot;
}

@property(retain, nonatomic) JTImageBadge *mineDot; // @synthesize mineDot=_mineDot;
- (void).cxx_destruct;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (void)reloadAppearMineTabDot;
- (void)reloadMineTabDotWith:(id)arg1;
- (void)requestMessageCount;
- (void)setupTabDot;
- (void)setupTabbar;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

