//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPPageMenuDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSString, SPPageMenu, UIScrollView;

@interface MessageCenterViewController : UIViewController <SPPageMenuDelegate, UIScrollViewDelegate>
{
    SPPageMenu *_pageMenu;
    UIScrollView *_msgScrollView;
    NSArray *_msgViewControllers;
}

@property(retain, nonatomic) NSArray *msgViewControllers; // @synthesize msgViewControllers=_msgViewControllers;
@property(retain, nonatomic) UIScrollView *msgScrollView; // @synthesize msgScrollView=_msgScrollView;
@property(retain, nonatomic) SPPageMenu *pageMenu; // @synthesize pageMenu=_pageMenu;
- (void).cxx_destruct;
- (void)pageMenu:(id)arg1 itemSelectedFromIndex:(long long)arg2 toIndex:(long long)arg3;
- (void)pageMenu:(id)arg1 itemSelectedAtIndex:(long long)arg2;
- (void)setupMsgScrollView;
- (void)setupPageMenuView;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

