//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CKList, JTImageBadge, NSString, UIButton, UIImageView, UILabel, UITableView, UIView;

@interface MineViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    UIView *_headerView;
    UIButton *_msgBtn;
    JTImageBadge *_msgDot;
    UIButton *_loginBtn;
    UIImageView *_avatarView;
    UILabel *_nickNameLb;
    UILabel *_phoneLb;
    UIImageView *_arrowView;
    CKList *_datasource;
}

@property(retain, nonatomic) CKList *datasource; // @synthesize datasource=_datasource;
@property(nonatomic) __weak UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(nonatomic) __weak UILabel *phoneLb; // @synthesize phoneLb=_phoneLb;
@property(nonatomic) __weak UILabel *nickNameLb; // @synthesize nickNameLb=_nickNameLb;
@property(nonatomic) __weak UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(nonatomic) __weak UIButton *loginBtn; // @synthesize loginBtn=_loginBtn;
@property(retain, nonatomic) JTImageBadge *msgDot; // @synthesize msgDot=_msgDot;
@property(nonatomic) __weak UIButton *msgBtn; // @synthesize msgBtn=_msgBtn;
@property(nonatomic) __weak UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)createCellInfo;
- (void)observerUserInfo;
- (void)fetchUserInfo;
- (void)reloadData;
- (void)actionToMsgBoxVC;
- (void)actionToMyInfoVC;
- (void)reloadAppearMineTabDot;
- (void)reloadMineTabDotWith:(id)arg1;
- (void)setupTabDot;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

