//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSString;

@interface ModifyUserInfoOp : BaseOp
{
    unsigned long long _type;
    NSString *_req_avatar;
    NSString *_req_nickName;
    NSString *_req_sign;
    NSString *_req_email;
}

@property(copy, nonatomic) NSString *req_email; // @synthesize req_email=_req_email;
@property(copy, nonatomic) NSString *req_sign; // @synthesize req_sign=_req_sign;
@property(copy, nonatomic) NSString *req_nickName; // @synthesize req_nickName=_req_nickName;
@property(copy, nonatomic) NSString *req_avatar; // @synthesize req_avatar=_req_avatar;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

