//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@interface MsgCountOp : BaseOp
{
    long long _rsp_unReadCount;
}

@property(nonatomic) long long rsp_unReadCount; // @synthesize rsp_unReadCount=_rsp_unReadCount;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

