//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@interface MsgMarkOp : BaseOp
{
    long long _msgId;
}

@property(nonatomic) long long msgId; // @synthesize msgId=_msgId;
- (id)rac_postRequest;

@end

