//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MultiMediaManager : NSObject
{
}

+ (id)sharedManager;
- (id)urlWith:(id)arg1 imageType:(long long)arg2;
- (id)urlWith:(id)arg1 scaleSize:(struct CGSize)arg2;
- (id)urlWith:(id)arg1 croppedSize:(struct CGSize)arg2;
- (id)rac_getImageByUrl:(id)arg1 withType:(long long)arg2 defaultPic:(id)arg3 errorPic:(id)arg4;
- (void)saveImageToCache:(id)arg1 forUrl:(id)arg2;
- (_Bool)diskImageExistsForUrl:(id)arg1;
- (_Bool)cachedImageExistsForUrl:(id)arg1;
- (id)imageFromDiskCacheForUrl:(id)arg1;
- (id)imageFromMemoryCacheForUrl:(id)arg1;

@end

