//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CKList, NSArray, NSLayoutConstraint, UIBarButtonItem, UIButton, UITableView, UIView;

@interface MyCollectionViewController : UIViewController
{
    _Bool _isEditing;
    UIBarButtonItem *_editButtionItem;
    UITableView *_tableView;
    UIButton *_allSelectBtn;
    UIButton *_deleteBtn;
    UIView *_bottomView;
    NSLayoutConstraint *_tableViewBottomConstraint;
    NSArray *_newsModelArray;
    CKList *_datasource;
}

@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(retain, nonatomic) CKList *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) NSArray *newsModelArray; // @synthesize newsModelArray=_newsModelArray;
@property(nonatomic) __weak NSLayoutConstraint *tableViewBottomConstraint; // @synthesize tableViewBottomConstraint=_tableViewBottomConstraint;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(nonatomic) __weak UIButton *allSelectBtn; // @synthesize allSelectBtn=_allSelectBtn;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIBarButtonItem *editButtionItem; // @synthesize editButtionItem=_editButtionItem;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)createCellItem:(id)arg1;
- (void)reloadDatasource;
- (void)getMyCollectionInfo;
- (void)actionDelete;
- (void)actionAllSelect;
- (void)actionFinish;
- (void)actionEdit;
- (void)refreshBottomView;
- (void)refreshNavigationBar;
- (void)setupBottomView;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

