//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class CKList, UIImage, UITableView;

@interface MyInfoViewController : UIViewController
{
    UITableView *_tableView;
    CKList *_datasource;
    UIImage *_avatarImg;
}

@property(retain, nonatomic) UIImage *avatarImg; // @synthesize avatarImg=_avatarImg;
@property(retain, nonatomic) CKList *datasource; // @synthesize datasource=_datasource;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reloadData;
- (void)pickerAvatar:(id)arg1;
- (void)setupSignals;
- (void)actionLogout;
- (void)actionBack;
- (void)setupNavigationBar;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

