//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPRequestOperationManager, NSString;

@interface NetworkManager : NSObject
{
    _Bool _simulateResponse;
    NSString *_skey;
    NSString *_token;
    NSString *_bindingMobile;
    NSString *_apiServer;
    AFHTTPRequestOperationManager *_apiManager;
    AFHTTPRequestOperationManager *_mediaClient;
    double _simulateResponseDelay;
    CDUnknownBlockType _catchErrorHandler;
}

+ (id)sharedManager;
@property(copy, nonatomic) CDUnknownBlockType catchErrorHandler; // @synthesize catchErrorHandler=_catchErrorHandler;
@property(nonatomic) double simulateResponseDelay; // @synthesize simulateResponseDelay=_simulateResponseDelay;
@property(nonatomic) _Bool simulateResponse; // @synthesize simulateResponse=_simulateResponse;
@property(readonly, nonatomic) AFHTTPRequestOperationManager *mediaClient; // @synthesize mediaClient=_mediaClient;
@property(readonly, nonatomic) AFHTTPRequestOperationManager *apiManager; // @synthesize apiManager=_apiManager;
@property(readonly, nonatomic) NSString *apiServer; // @synthesize apiServer=_apiServer;
@property(retain, nonatomic) NSString *bindingMobile; // @synthesize bindingMobile=_bindingMobile;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(retain, nonatomic) NSString *skey; // @synthesize skey=_skey;
- (void).cxx_destruct;
- (void)handleError:(id)arg1 forOp:(id)arg2;
- (id)init;

@end

