//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAIndexedSubscript.h"
#import "NSFastEnumeration.h"
#import "NSObject.h"

@class NSArray;

@protocol NSAArrayLikeDataObject <NSObject, NSFastEnumeration, NSAIndexedSubscript>
@property(readonly, copy) NSArray *allObjects;
@property(readonly, nonatomic) unsigned long long count;
- (id):(unsigned long long)arg1;
- (_Bool)containsObject:(id)arg1;
- (unsigned long long)indexOfObject:(id)arg1;
- (id)objectAtIndex:(unsigned long long)arg1;
@end

