//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSAClass : NSObject
{
    Class _class;
}

+ (id)classWithName:(id)arg1;
+ (id)classWithUTF8Name:(const char *)arg1;
+ (id)classWithClass:(Class)arg1;
@property(readonly, nonatomic) Class class; // @synthesize class=_class;
- (id)initWithClass:(Class)arg1;

@end

