//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSATriple.h"

#import "NSAMutableArrayLikeDataObject.h"

@class NSArray, NSString;

@interface NSAMutableTriple : NSATriple <NSAMutableArrayLikeDataObject>
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setTriple:(id)arg1;
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (void)replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
@property(retain, nonatomic) id third; // @dynamic third;
@property(retain, nonatomic) id second; // @dynamic second;
@property(retain, nonatomic) id first; // @dynamic first;

// Remaining properties
@property(readonly, copy) NSArray *allObjects;
@property(readonly, nonatomic) unsigned long long count;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

