//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAArrayLikeDataObject.h"
#import "NSAMutableIndexedSubscript.h"

@protocol NSAMutableArrayLikeDataObject <NSAArrayLikeDataObject, NSAMutableIndexedSubscript>
- (void)replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
@end

