//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@class NSMutableOrderedSet;

@interface NSAMutableOrderedDictionary : NSMutableDictionary
{
    NSMutableDictionary *_impl;
    NSMutableOrderedSet *_order;
}

+ (id)dictionaryWithImplementationOrder:(id)arg1 dictionary:(id)arg2;
- (void).cxx_destruct;
- (id)reversedKeyEnumerator;
- (unsigned long long)indexOfKey:(id)arg1;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)keyAtIndex:(unsigned long long)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;
- (id)descriptionInStringsFileFormat;
- (id)keyEnumerator;
- (id)objectForKey:(id)arg1;
- (unsigned long long)count;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithObjects:(const id *)arg1 forKeys:(const id *)arg2 count:(unsigned long long)arg3;
- (id)init;
- (id)initWithImplementationOrder:(id)arg1 dictionary:(id)arg2;

@end

