//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSAOverridingMediator : NSObject
{
    id _origin;
    id _override;
    _Bool _suppressive;
}

+ (id)mediatorWithOrigin:(id)arg1 override:(id)arg2 suppressive:(_Bool)arg3;
+ (id)mediatorWithOrigin:(id)arg1 override:(id)arg2;
@property(nonatomic) _Bool suppressive; // @synthesize suppressive=_suppressive;
@property(retain, nonatomic) id override; // @synthesize override=_override;
@property(retain, nonatomic) id origin; // @synthesize origin=_origin;
- (void).cxx_destruct;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)initWithOrigin:(id)arg1 override:(id)arg2 suppressive:(_Bool)arg3;

@end

