//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (Creations)
+ (id)arrayWithEnumerator:(id)arg1;
+ (id)arrayWithData:(id)arg1 format:(unsigned long long *)arg2 error:(id *)arg3;
+ (id)arrayWithData:(id)arg1;
- (id)subarrayFromIndex:(unsigned long long)arg1 length:(unsigned long long)arg2;
- (id)subarrayFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (id)subarrayToIndex:(unsigned long long)arg1;
- (id)subarrayFromIndex:(unsigned long long)arg1;
- (id)initWithEnumerator:(id)arg1 copyItems:(_Bool)arg2;
- (id)initWithEnumerator:(id)arg1;
- (id)initWithData:(id)arg1 format:(unsigned long long *)arg2 error:(id *)arg3;
- (id)initWithData:(id)arg1;
@end

