//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (CreationRC)
+ (id)arrayWithObject:(id)arg1 count:(unsigned long long)arg2;
- (id)initWithObjectCopy:(id)arg1 count:(unsigned long long)arg2 mutable:(_Bool)arg3;
- (id)initWithObject:(id)arg1 count:(unsigned long long)arg2;
@end

