//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAMutableDictionary.h"

@class NSNumber, NSParagraphStyle, NSShadow, UIColor, UIFont;

@interface NSAttributedStringAttributeDictionary : NSAMutableDictionary
{
}

@property unsigned long long verticalGlyphForm;
@property(retain) NSNumber *verticalGlyphFormNumber;
@property(retain) NSShadow *shadow;
@property float strokeWidth;
@property(retain) NSNumber *strokeWidthNumber;
@property(retain) UIColor *strokeColor;
@property long long underlineStyle;
@property(retain) NSNumber *underlineStyleNumber;
@property long long strikethroughStyle;
@property(retain) NSNumber *strikethroughStyleNumber;
@property float kern;
@property(retain) NSNumber *kernNumber;
@property(retain) NSNumber *ligatureNumber;
@property(retain) UIColor *backgroundColor;
@property(retain) UIColor *foregroundColor;
@property(retain) NSParagraphStyle *paragraphStyle;
@property(retain) UIFont *font;
@property unsigned long long ligature;
- (void)setObject:(id)arg1 forKey:(id)arg2;

@end

