//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSAArrayLikeDataObject.h"
#import "NSCopying.h"
#import "NSMutableCopying.h"

@class NSArray, NSString;

@interface NSATuple : NSObject <NSCopying, NSMutableCopying, NSAArrayLikeDataObject>
{
    id _first;
    id _second;
}

+ (id)tupleWithFirst:(id)arg1 second:(id)arg2;
+ (id)tuple;
- (void).cxx_destruct;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSArray *allObjects;
- (_Bool)containsObject:(id)arg1;
- (unsigned long long)indexOfObject:(id)arg1;
- (id):(unsigned long long)arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)objectAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long count;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToTuple:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) id second;
@property(readonly, nonatomic) id first;
- (id)initWithFirst:(id)arg1 second:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

