//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface NSAURLRequestHTTPBodyMultiPartFormPostFormatter : NSObject
{
    NSMutableData *_body;
    unsigned long long _encoding;
}

+ (id)_bodyBoundaryWithEncoding:(unsigned long long)arg1;
+ (id)_bodyBoundaryString;
- (void).cxx_destruct;
- (id)_bodyBoundary;
- (id)_bodyBoundaryString;
- (id)HTTPBody;
- (void)appendBodyDataEndian;
- (void)appendBodyDataToFieldName:(id)arg1 fileName:(id)arg2 data:(id)arg3;
- (void)appendBodyDataToFieldName:(id)arg1 data:(id)arg2;
- (void)appendBodyDataToFieldName:(id)arg1 text:(id)arg2;
- (void)appendBodyDataToFieldName:(id)arg1 text:(id)arg2 encoding:(unsigned long long)arg3;
- (void)_appendBodyBoundaryWithEncoding:(unsigned long long)arg1;
- (id)initWithEncoding:(unsigned long long)arg1;
- (id)init;

@end

