//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NSAVersion : NSObject
{
    NSString *_string;
    long long _major;
    long long _minor;
    long long _bugfix;
}

+ (id)versionWithString:(id)arg1;
@property(readonly, nonatomic) long long bugfix; // @synthesize bugfix=_bugfix;
@property(readonly, nonatomic) long long minor; // @synthesize minor=_minor;
@property(readonly, nonatomic) long long major; // @synthesize major=_major;
@property(readonly, nonatomic) NSString *string; // @synthesize string=_string;
- (void).cxx_destruct;
- (id)initWithString:(id)arg1;

@end

