//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCountedSet.h"

@interface NSCountedSet (Functional)
- (id)arrayByFilteringOperatorWithCount:(CDUnknownBlockType)arg1;
- (id)arrayByMapFilteringOperatorWithCount:(CDUnknownBlockType)arg1;
- (id)arrayByMappingOperatorWithCount:(CDUnknownBlockType)arg1;
- (void)applyProcedureWithCount:(CDUnknownBlockType)arg1;
@end

