//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (CommonCryptorString)
- (id)decrypted3DESStringWithKey:(id)arg1;
- (id)decryptedAES256StringWithKey:(id)arg1;
- (id)decryptedAES128StringWithKey:(id)arg1;
@end

