//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Serialization)
+ (id)dataWithHexadecimalString:(id)arg1;
- (id)initWithHexadecimalString:(id)arg1;
- (id)hexadecimalString;
- (id)propertyListObjectUsingFormat:(unsigned long long *)arg1 error:(id *)arg2;
@end

