//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Deprecation)
+ (id)dataWithBase64String:(id)arg1;
- (id)initWithBase64String:(id)arg1;
- (id)base64String;
@end

