//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (DateForText)
+ (_Bool)isDateValidWithBegin:(id)arg1 andEnd:(id)arg2;
+ (id)dateFormatStringForRefrenceTimeInteval:(double)arg1;
+ (id)dateWithText:(id)arg1;
+ (id)dateWithD14Text:(id)arg1;
+ (id)dateWithUTS:(id)arg1;
+ (id)dateWithD10Text:(id)arg1;
+ (id)dateWithD8Text:(id)arg1;
+ (id)dateFormatForYYYYMMddHHmmWithD15:(id)arg1;
- (id)dateFormatForDT8;
- (id)dateFormatForDT15;
- (id)dateFormatForRefrenceText;
- (id)dateFormatForText;
- (id)dateFormatForYYMM;
- (id)dateFormatForSimpleYYMM;
- (id)dateFormatForYYYYMMddHHmmss;
- (id)dateFormatForYYYYMMddHHmm2;
- (id)dateFormatForYYYYMMddHHmm;
- (id)dateFormatForD10;
- (id)dateFormatForYYMMdd2;
- (id)dateFormatForYYMMdd;
- (id)textForDate;
@end

