//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (CommonDigest)
- (id)digestStringBySHA1;
- (id)digestStringByMD5;
- (id)digestBySHA512;
- (id)digestBySHA384;
- (id)digestBySHA256;
- (id)digestBySHA224;
- (id)digestBySHA1;
- (id)digestByMD5;
- (id)digestByMD4;
- (id)digestByMD2;
@end

