//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (NSURL_deprecated)
+ (id)dataWithContentsOfAbstractPath:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
+ (id)dataWithContentsOfAbstractPath:(id)arg1;
- (id)initWithContentsOfAbstractPath:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
- (id)initWithContentsOfAbstractPath:(id)arg1;
@end

