//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (CommonCryptor)
- (id)decryptedRC4DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)decryptedRC2DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)decryptedCastDataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)decrypted3DESDataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)decryptedDESDataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)decryptedAES256DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)decryptedAES192DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)decryptedAES128DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)decrypted3DESDataWithKey:(id)arg1;
- (id)decryptedAES256DataWithKey:(id)arg1;
- (id)decryptedAES128DataWithKey:(id)arg1;
- (id)encryptedRC4DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)encryptedRC2DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)encryptedCastDataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)encrypted3DESDataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)encryptedDESDataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)encryptedAES256DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)encryptedAES192DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)encryptedAES128DataWithKey:(id)arg1 options:(unsigned int)arg2;
- (id)encrypted3DESDataWithKey:(id)arg1;
- (id)encryptedAES256DataWithKey:(id)arg1;
- (id)encryptedAES128DataWithKey:(id)arg1;
@end

