//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (NSURLRequest)
+ (id)dataWithContentsOfURL:(id)arg1 postBody:(id)arg2 encoding:(unsigned long long)arg3;
+ (id)dataWithContentsOfURLRequest:(id)arg1 error:(id *)arg2;
+ (id)dataWithContentsOfURLRequest:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1 postBody:(id)arg2 encoding:(unsigned long long)arg3;
- (id)initWithContentsOfURLRequest:(id)arg1 error:(id *)arg2;
- (id)initWithContentsOfURLRequest:(id)arg1;
@end

