//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (GetParams)
- (int)intParamForName:(id)arg1;
- (double)doubleParamForName:(id)arg1;
- (long long)integerParamForName:(id)arg1;
- (float)floatParamForName:(id)arg1;
- (id)stringParamForName:(id)arg1;
- (id)numberParamForName:(id)arg1;
- (_Bool)boolParamForName:(id)arg1;
@end

