//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (Functional)
- (id)firstKeyByFilteringOperatorWithKey:(CDUnknownBlockType)arg1;
- (id)firstObjectByFilteringOperatorWithKey:(CDUnknownBlockType)arg1;
- (id)firstObjectByFilteringOperator:(CDUnknownBlockType)arg1;
- (id)dictionaryByFilteringOperatorWithKey:(CDUnknownBlockType)arg1;
- (id)dictionaryByFilteringOperator:(CDUnknownBlockType)arg1;
- (id)dictionaryByMapFilteringOperatorWithKey:(CDUnknownBlockType)arg1;
- (id)dictionaryByMapFilteringOperator:(CDUnknownBlockType)arg1;
- (id)dictionaryByMappingOperatorWithKey:(CDUnknownBlockType)arg1;
- (id)dictionaryByMappingOperator:(CDUnknownBlockType)arg1;
- (void)applyProcedureWithKey:(CDUnknownBlockType)arg1;
@end

