//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableArray.h"

@interface NSMutableArray (Functional)
- (void)filterWithIndex:(CDUnknownBlockType)arg1;
- (void)filter:(CDUnknownBlockType)arg1;
- (void)mapFilterWithIndex:(CDUnknownBlockType)arg1;
- (void)mapFilter:(CDUnknownBlockType)arg1;
- (void)mapWithIndex:(CDUnknownBlockType)arg1;
- (void)map:(CDUnknownBlockType)arg1;
@end

