//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableAttributedString.h"

@interface NSMutableAttributedString (AttributeProperties)
- (void)removeAttributeVerticalGlyphFormFromRange:(struct _NSRange)arg1;
- (void)addAttributeVerticalGlyphForm:(unsigned long long)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeShadowFromRange:(struct _NSRange)arg1;
- (void)addAttributeShadow:(id)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeStrokeWidthFromRange:(struct _NSRange)arg1;
- (void)addAttributeStrokeWidth:(float)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeStrokeColorFromRange:(struct _NSRange)arg1;
- (void)addAttributeStrokeColor:(id)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeUnderlineStyleFromRange:(struct _NSRange)arg1;
- (void)addAttributeUnderlineStyle:(long long)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeStrikethroughStyleFromRange:(struct _NSRange)arg1;
- (void)addAttributeStrikethroughStyle:(long long)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeKernFromRange:(struct _NSRange)arg1;
- (void)addAttributeKern:(float)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeLigatureFromRange:(struct _NSRange)arg1;
- (void)addAttributeLigature:(unsigned long long)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeBackgroundColorFromRange:(struct _NSRange)arg1;
- (void)addAttributeBackgroundColor:(id)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeForegroundColorFromRange:(struct _NSRange)arg1;
- (void)addAttributeForegroundColor:(id)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeParagraphStyleFromRange:(struct _NSRange)arg1;
- (void)addAttributeParagraphStyle:(id)arg1 range:(struct _NSRange)arg2;
- (void)removeAttributeFontFromRange:(struct _NSRange)arg1;
- (void)addAttributeFont:(id)arg1 range:(struct _NSRange)arg2;
@end

