//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@interface NSMutableDictionary (Functional)
- (void)filterWithKey:(CDUnknownBlockType)arg1;
- (void)filter:(CDUnknownBlockType)arg1;
- (void)mapFilterWithKey:(CDUnknownBlockType)arg1;
- (void)mapFilter:(CDUnknownBlockType)arg1;
- (void)mapWithKey:(CDUnknownBlockType)arg1;
- (void)map:(CDUnknownBlockType)arg1;
@end

