//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableURLRequest.h"

@class NSData, NSDictionary, NSInputStream, NSString, NSURL;

@interface NSMutableURLRequest (Properties)

// Remaining properties
@property(retain) NSData *HTTPBody; // @dynamic HTTPBody;
@property(retain) NSInputStream *HTTPBodyStream; // @dynamic HTTPBodyStream;
@property(retain) NSString *HTTPMethod; // @dynamic HTTPMethod;
@property _Bool HTTPShouldHandleCookies; // @dynamic HTTPShouldHandleCookies;
@property _Bool HTTPShouldUsePipelining; // @dynamic HTTPShouldUsePipelining;
@property(retain) NSURL *URL; // @dynamic URL;
@property(retain) NSDictionary *allHTTPHeaderFields; // @dynamic allHTTPHeaderFields;
@property unsigned long long cachePolicy; // @dynamic cachePolicy;
@property(retain) NSURL *mainDocumentURL; // @dynamic mainDocumentURL;
@property unsigned long long networkServiceType; // @dynamic networkServiceType;
@property double timeoutInterval; // @dynamic timeoutInterval;
@end

