//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableArray.h"

@interface NSMutableArray (Safety)
- (_Bool)safetyAddObjectsFromArray:(id)arg1;
- (_Bool)safetyInsertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (_Bool)safetyReplaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (_Bool)safetyRemoveObject:(id)arg1;
- (id)safetyRemoveObjectsInRange:(struct _NSRange)arg1;
- (id)safetyRemoveObjectsBeforeIndex:(unsigned long long)arg1;
- (id)safetyRemoveObjectsFromIndex:(unsigned long long)arg1;
- (_Bool)safetyRemoveObjectAtIndex:(unsigned long long)arg1;
- (_Bool)safetyExchangeObjectAtIndex:(unsigned long long)arg1 withObjectAtIndex:(unsigned long long)arg2;
- (_Bool)safetyAddObject:(id)arg1;
@end

