//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNull.h"

@interface NSNull (Tools)
+ (id)nilIfObjectIsNull:(id)arg1;
+ (id)nullIfObjectIsNil:(id)arg1;
+ (_Bool)objectIsNilOrNull:(id)arg1;
+ (_Bool)objectIsNull:(id)arg1;
@end

