//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface NSObject (Runtime)
@property(nonatomic) __weak id customWeakObject; // @dynamic customWeakObject;
@property(copy, nonatomic) CDUnknownBlockType customActionBlock; // @dynamic customActionBlock;
@property(retain, nonatomic) NSMutableArray *customArray; // @dynamic customArray;
@property(retain, nonatomic) NSMutableDictionary *customInfo; // @dynamic customInfo;
@property(retain, nonatomic) id customObject; // @dynamic customObject;
@property(retain, nonatomic) NSString *customIdenfitier; // @dynamic customIdenfitier;
@property(nonatomic) long long customTag; // @dynamic customTag;
@end

