//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (ObjCRuntimeRC)
- (void)setAndCopyVariable:(id)arg1 forName:(id)arg2;
- (void)setAndRetainVariable:(id)arg1 forName:(id)arg2;
- (void)setVariable:(void *)arg1 forName:(id)arg2;
- (void)getVariable:(void **)arg1 forName:(id)arg2;
- (id)variableForName:(id)arg1;
@end

