//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOrderedSet.h"

@interface NSOrderedSet (Functional)
- (id)setByFilteringOperatorWithIndex:(CDUnknownBlockType)arg1;
- (id)setByFilteringOperator:(CDUnknownBlockType)arg1;
- (id)setByMapFilteringOperatorWithIndex:(CDUnknownBlockType)arg1;
- (id)setByMapFilteringOperator:(CDUnknownBlockType)arg1;
- (id)setByMappingOperatorWithIndex:(CDUnknownBlockType)arg1;
- (id)setByMappingOperator:(CDUnknownBlockType)arg1;
- (id)reduce:(CDUnknownBlockType)arg1 initialObject:(id)arg2;
- (id)reduce:(CDUnknownBlockType)arg1;
- (id)arrayByFilteringOperatorWithIndex:(CDUnknownBlockType)arg1;
- (id)arrayByFilteringOperator:(CDUnknownBlockType)arg1;
- (id)arrayByMapFilteringOperatorWithIndex:(CDUnknownBlockType)arg1;
- (id)arrayByMapFilteringOperator:(CDUnknownBlockType)arg1;
- (id)arrayByMappingOperatorWithIndex:(CDUnknownBlockType)arg1;
- (id)arrayByMappingOperator:(CDUnknownBlockType)arg1;
- (void)applyProcedureWithIndex:(CDUnknownBlockType)arg1;
- (void)applyProcedure:(CDUnknownBlockType)arg1;
@end

