//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Shortcuts)
- (id)stringByTrimmingNewlineCharacters;
- (id)stringByTrimmingWhitespaceAndNewlineCharacters;
- (id)stringByTrimmingWhitespaceCharacters;
- (id)substringFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (id)substringFromIndex:(unsigned long long)arg1 length:(unsigned long long)arg2;
- (struct _NSRange)range;
- (id)format0:(id)arg1;
- (id)format:(id)arg1;
@end

