//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Format)
+ (id)formatForRoundPrice3:(double)arg1;
+ (id)formatForRoundPrice2:(double)arg1;
+ (id)formatForRoundPrice:(double)arg1;
+ (id)formatForFloorPrice:(double)arg1;
@end

