//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (NSURL)
- (id)abstractURL;
- (_Bool)hasURLPrefix;
- (id)pathProtocol;
- (id)smartURL;
- (id)temporaryURL;
- (id)configurationURL;
- (id)resourceURL;
- (id)fileURL;
- (id)URL;
- (id)URLProtocol;
- (_Bool)hasSmartURLPrefix;
- (_Bool)hasHTTPPrefix;
- (id)stringByAddingPercentEncodingForURLQuery;
- (id)stringByAddingPercentEncodingWithoutAllowedCharacters;
@end

