//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Creations)
+ (id)stringWithFormat:(id)arg1 arguments:(char *)arg2;
+ (id)stringWithConcatnatingStrings:(id)arg1;
+ (id)stringWithData:(id)arg1 encoding:(unsigned long long)arg2;
+ (id)stringWithInteger:(long long)arg1;
- (id)initWithConcatnatingStrings:(id)arg1;
- (id)initWithInteger:(long long)arg1;
@end

