//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (CommonCrypto)
- (id)digestStringBySHA1;
- (id)digestStringByMD5;
- (id)digestBySHA1;
- (id)digestByMD5;
- (id)digestBySHA512UsingEncoding:(unsigned long long)arg1;
- (id)digestBySHA384UsingEncoding:(unsigned long long)arg1;
- (id)digestBySHA256UsingEncoding:(unsigned long long)arg1;
- (id)digestBySHA224UsingEncoding:(unsigned long long)arg1;
- (id)digestBySHA1UsingEncoding:(unsigned long long)arg1;
- (id)digestByMD5UsingEncoding:(unsigned long long)arg1;
- (id)digestByMD4UsingEncoding:(unsigned long long)arg1;
- (id)digestByMD2UsingEncoding:(unsigned long long)arg1;
@end

