//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTimer.h"

@interface NSTimer (DelegateRC)
+ (id)scheduledTimerWithTimeInterval:(double)arg1 delegate:(id)arg2;
+ (id)timerWithTimeInterval:(double)arg1 delegate:(id)arg2;
- (id)initWithFireDate:(id)arg1 interval:(double)arg2 delegate:(id)arg3;
@end

