//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (Creations)
+ (id)fileURLWithFormat:(id)arg1;
+ (id)URLWithAbstractFormat:(id)arg1;
+ (id)URLWithAbstractPath:(id)arg1;
+ (id)URLWithFormat:(id)arg1;
+ (id)smartURLWithPath:(id)arg1;
+ (id)temporaryURLWithPath:(id)arg1;
+ (id)configurationURLWithPath:(id)arg1;
+ (id)resourceURLWithPath:(id)arg1;
- (id)initFileURLWithFormat:(id)arg1;
- (id)initWithFormat:(id)arg1;
- (id)initWithAbstractFormat:(id)arg1;
- (id)initWithAbstractPath:(id)arg1;
- (id)initSmartURLWithPath:(id)arg1;
- (id)initTemporaryURLWithPath:(id)arg1;
- (id)initConfigurationURLWithPath:(id)arg1;
- (id)initResourceURLWithPath:(id)arg1;
@end

