//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLRequest.h"

@interface NSURLRequest (Creations_deprecated)
+ (id)URLRequestWithAbstractPathFormat:(id)arg1;
+ (id)URLRequestWithAbstractPath:(id)arg1;
+ (id)URLRequestWithFilePathFormat:(id)arg1;
+ (id)URLRequestWithFilePath:(id)arg1;
+ (id)URLRequestWithURLFormat:(id)arg1;
- (id)initWithAbstractPathFormat:(id)arg1;
- (id)initWithAbstractPath:(id)arg1;
- (id)initWithFilePathFormat:(id)arg1;
- (id)initWithFilePath:(id)arg1;
- (id)initWithURLFormat:(id)arg1;
@end

