//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLRequest.h"

@class NSData, NSDictionary, NSInputStream, NSString, NSURL;

@interface NSURLRequest (Properties)

// Remaining properties
@property(readonly) NSData *HTTPBody; // @dynamic HTTPBody;
@property(readonly) NSInputStream *HTTPBodyStream; // @dynamic HTTPBodyStream;
@property(readonly) NSString *HTTPMethod; // @dynamic HTTPMethod;
@property(readonly) _Bool HTTPShouldHandleCookies; // @dynamic HTTPShouldHandleCookies;
@property(readonly) _Bool HTTPShouldUsePipelining; // @dynamic HTTPShouldUsePipelining;
@property(readonly) NSURL *URL; // @dynamic URL;
@property(readonly) NSDictionary *allHTTPHeaderFields; // @dynamic allHTTPHeaderFields;
@property(readonly) unsigned long long cachePolicy; // @dynamic cachePolicy;
@property(readonly) NSURL *mainDocumentURL; // @dynamic mainDocumentURL;
@property(readonly) unsigned long long networkServiceType; // @dynamic networkServiceType;
@property(readonly) double timeoutInterval; // @dynamic timeoutInterval;
@end

