//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSArray;

@interface OrderListGetOp : BaseOp
{
    long long _status;
    long long _pageNo;
    long long _pageSize;
    NSArray *_rsp_orderList;
}

@property(retain, nonatomic) NSArray *rsp_orderList; // @synthesize rsp_orderList=_rsp_orderList;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long pageNo; // @synthesize pageNo=_pageNo;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

