//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UISearchBarDelegate.h"

@class CKList, JXTableView, NSString, RACDisposable, UIAlertView, UISearchBar;

@interface OrderViewController : UIViewController <UISearchBarDelegate>
{
    _Bool _isLoading;
    _Bool _isRemain;
    _Bool _isRequested;
    UISearchBar *_searchBar;
    JXTableView *_tableView;
    long long _filterStatus;
    CKList *_datasource;
    long long _currentPageNum;
    UIAlertView *_alertView;
    RACDisposable *_disposable;
}

@property(retain, nonatomic) RACDisposable *disposable; // @synthesize disposable=_disposable;
@property(nonatomic) _Bool isRequested; // @synthesize isRequested=_isRequested;
@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
@property(nonatomic) long long currentPageNum; // @synthesize currentPageNum=_currentPageNum;
@property(nonatomic) _Bool isRemain; // @synthesize isRemain=_isRemain;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) CKList *datasource; // @synthesize datasource=_datasource;
@property(nonatomic) long long filterStatus; // @synthesize filterStatus=_filterStatus;
@property(nonatomic) __weak JXTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void).cxx_destruct;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)createCellItem:(id)arg1;
- (id)createFilterCell;
- (id)createNoneCell;
- (void)cleanDatasource;
- (void)getMoreOrder;
- (void)requestOrderInfo;
- (void)setupObserver;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

