//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PhoneHelper : NSObject
{
    _Bool _exsitBaiduMap;
    _Bool _exsitAMap;
    _Bool _exsitWechat;
}

+ (id)sharedHelper;
@property(nonatomic) _Bool exsitWechat; // @synthesize exsitWechat=_exsitWechat;
@property(nonatomic) _Bool exsitAMap; // @synthesize exsitAMap=_exsitAMap;
@property(nonatomic) _Bool exsitBaiduMap; // @synthesize exsitBaiduMap=_exsitBaiduMap;
- (_Bool)handleCameraAuthStatusDenied;
- (_Bool)isCameraAuthStatusAllowed;
- (void)makePhone:(id)arg1 andInfo:(id)arg2;
- (void)makePhone:(id)arg1;
- (id)init;

@end

