//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "HooDatePickerDelegate.h"

@class CKList, HooDatePicker, JXTableView, NSDate, NSString, RACDisposable, UIAlertView, UILabel, UIView;

@interface PointViewController : UIViewController <HooDatePickerDelegate>
{
    _Bool _isLoading;
    _Bool _isRemain;
    _Bool _isRequested;
    UILabel *_totalBonusLb;
    UILabel *_totalInfoLb;
    JXTableView *_tableView;
    HooDatePicker *_datePicker;
    CKList *_datasource;
    long long _currentPageNum;
    NSDate *_filterMonth;
    UIAlertView *_alertView;
    RACDisposable *_disposable;
    UIView *_navigationBarLine;
}

@property(retain, nonatomic) UIView *navigationBarLine; // @synthesize navigationBarLine=_navigationBarLine;
@property(retain, nonatomic) RACDisposable *disposable; // @synthesize disposable=_disposable;
@property(nonatomic) _Bool isRequested; // @synthesize isRequested=_isRequested;
@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) NSDate *filterMonth; // @synthesize filterMonth=_filterMonth;
@property(nonatomic) long long currentPageNum; // @synthesize currentPageNum=_currentPageNum;
@property(nonatomic) _Bool isRemain; // @synthesize isRemain=_isRemain;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) CKList *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) HooDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(nonatomic) __weak JXTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UILabel *totalInfoLb; // @synthesize totalInfoLb=_totalInfoLb;
@property(nonatomic) __weak UILabel *totalBonusLb; // @synthesize totalBonusLb=_totalBonusLb;
- (void).cxx_destruct;
- (void)datePicker:(id)arg1 didClickOther:(id)arg2;
- (void)datePicker:(id)arg1 didSelectedDate:(id)arg2;
- (void)datePicker:(id)arg1 didCancel:(id)arg2;
- (void)datePicker:(id)arg1 dateDidChange:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)createCellItem:(id)arg1;
- (id)createFilterCell;
- (id)createNoneCell;
- (void)getMoreBonus;
- (void)requestBonusInfo;
- (void)cleanDatasource;
- (id)findHairlineImageViewUnder:(id)arg1;
- (void)actionToQuestion;
- (void)setupObserver;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

