//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SDPhotoBrowserDelegate.h"

@class CKList, FeedbackModel, NSString, UITableView, UIView;

@interface QADetailViewController : UIViewController <SDPhotoBrowserDelegate>
{
    FeedbackModel *_feedbackModel;
    UITableView *_tableView;
    CKList *_datasource;
    UIView *_thumbImgView;
}

@property(retain, nonatomic) UIView *thumbImgView; // @synthesize thumbImgView=_thumbImgView;
@property(retain, nonatomic) CKList *datasource; // @synthesize datasource=_datasource;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) FeedbackModel *feedbackModel; // @synthesize feedbackModel=_feedbackModel;
- (void).cxx_destruct;
- (id)photoBrowser:(id)arg1 highQualityImageURLForIndex:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)createImgCellItem:(id)arg1 andContent:(id)arg2;
- (id)createInfoCellItem:(id)arg1 andContent:(id)arg2;
- (void)prepareDatasource;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

