//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextViewDelegate.h"

@class NSString, UIButton, UIImage, UIImageView, UILabel, UIScrollView, UITextField, UITextView, UIView;

@interface QAViewController : UIViewController <UITextViewDelegate>
{
    UIScrollView *_scrollView;
    UIView *_titleBgView;
    UITextField *_titleTextField;
    UIView *_contentBgView;
    UITextView *_contentTextField;
    UILabel *_contentPlaceHolder;
    UILabel *_policyNoTipsLabel;
    UIView *_policyNoBgView;
    UITextField *_policyNoTextField;
    UILabel *_insurerTipsLabel;
    UIView *_insurerBgView;
    UITextField *_insurerTextField;
    UILabel *_picTipsLabel;
    UIView *_picBgView;
    UIImageView *_picImgView;
    UIButton *_sureBtn;
    UIImage *_thumbnail;
    NSString *_thumbnailUrl;
}

@property(retain, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(retain, nonatomic) UIImage *thumbnail; // @synthesize thumbnail=_thumbnail;
@property(retain, nonatomic) UIButton *sureBtn; // @synthesize sureBtn=_sureBtn;
@property(retain, nonatomic) UIImageView *picImgView; // @synthesize picImgView=_picImgView;
@property(retain, nonatomic) UIView *picBgView; // @synthesize picBgView=_picBgView;
@property(retain, nonatomic) UILabel *picTipsLabel; // @synthesize picTipsLabel=_picTipsLabel;
@property(retain, nonatomic) UITextField *insurerTextField; // @synthesize insurerTextField=_insurerTextField;
@property(retain, nonatomic) UIView *insurerBgView; // @synthesize insurerBgView=_insurerBgView;
@property(retain, nonatomic) UILabel *insurerTipsLabel; // @synthesize insurerTipsLabel=_insurerTipsLabel;
@property(retain, nonatomic) UITextField *policyNoTextField; // @synthesize policyNoTextField=_policyNoTextField;
@property(retain, nonatomic) UIView *policyNoBgView; // @synthesize policyNoBgView=_policyNoBgView;
@property(retain, nonatomic) UILabel *policyNoTipsLabel; // @synthesize policyNoTipsLabel=_policyNoTipsLabel;
@property(retain, nonatomic) UILabel *contentPlaceHolder; // @synthesize contentPlaceHolder=_contentPlaceHolder;
@property(retain, nonatomic) UITextView *contentTextField; // @synthesize contentTextField=_contentTextField;
@property(retain, nonatomic) UIView *contentBgView; // @synthesize contentBgView=_contentBgView;
@property(retain, nonatomic) UITextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property(retain, nonatomic) UIView *titleBgView; // @synthesize titleBgView=_titleBgView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)textViewDidChange:(id)arg1;
- (void)pickImage;
- (void)actionSubmit;
- (void)actionToMyFeedback;
- (void)setupScrollView;
- (void)setupUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

