//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RACDisposable.h"

@interface RACSerialDisposable : RACDisposable
{
    void *_disposablePtr;
}

+ (id)serialDisposableWithDisposable:(id)arg1;
- (void)dispose;
- (id)swapInDisposable:(id)arg1;
- (void)dealloc;
- (id)initWithBlock:(CDUnknownBlockType)arg1;
- (id)init;
@property(retain) RACDisposable *disposable;
- (_Bool)isDisposed;

@end

