//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, SDPhotoBrowser, UIImage;

@protocol SDPhotoBrowserDelegate <NSObject>
- (UIImage *)photoBrowser:(SDPhotoBrowser *)arg1 placeholderImageForIndex:(long long)arg2;

@optional
- (NSURL *)photoBrowser:(SDPhotoBrowser *)arg1 highQualityImageURLForIndex:(long long)arg2;
@end

