//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIActivityIndicatorView, UIButton, UILabel, UIScrollView;

@interface SDPhotoBrowser : UIView <UIScrollViewDelegate>
{
    UIScrollView *_scrollView;
    _Bool _hasShowedFistView;
    UILabel *_indexLabel;
    UIButton *_saveButton;
    UIActivityIndicatorView *_indicatorView;
    _Bool _willDisappear;
    _Bool _showSaveBtn;
    _Bool _showIndexLabel;
    UIView *_sourceImagesContainerView;
    long long _currentImageIndex;
    long long _imageCount;
    unsigned long long _sourceImagesContainerViewContentMode;
    id <SDPhotoBrowserDelegate> _delegate;
}

@property(nonatomic) __weak id <SDPhotoBrowserDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long sourceImagesContainerViewContentMode; // @synthesize sourceImagesContainerViewContentMode=_sourceImagesContainerViewContentMode;
@property(nonatomic) _Bool showIndexLabel; // @synthesize showIndexLabel=_showIndexLabel;
@property(nonatomic) _Bool showSaveBtn; // @synthesize showSaveBtn=_showSaveBtn;
@property(nonatomic) long long imageCount; // @synthesize imageCount=_imageCount;
@property(nonatomic) long long currentImageIndex; // @synthesize currentImageIndex=_currentImageIndex;
@property(nonatomic) __weak UIView *sourceImagesContainerView; // @synthesize sourceImagesContainerView=_sourceImagesContainerView;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (id)highQualityImageURLForIndex:(long long)arg1;
- (id)placeholderImageForIndex:(long long)arg1;
- (void)showFirstImage;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)show;
- (void)layoutSubviews;
- (void)imageViewDoubleTaped:(id)arg1;
- (void)photoClick:(id)arg1;
- (void)setupImageOfImageViewForIndex:(long long)arg1;
- (void)setupScrollView;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveImage;
- (void)setupToolbars;
- (void)dealloc;
- (void)didMoveToSuperview;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

