//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSArray, NSString;

@interface SearchNewsOp : BaseOp
{
    NSString *_title;
    long long _currentPage;
    long long _pageSize;
    NSArray *_rsp_newsArray;
}

@property(retain, nonatomic) NSArray *rsp_newsArray; // @synthesize rsp_newsArray=_rsp_newsArray;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

