//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SYPageView, SYPaginatorView;

@protocol SYPaginatorViewDataSource <NSObject>
- (SYPageView *)paginatorView:(SYPaginatorView *)arg1 viewForPageAtIndex:(long long)arg2;
- (long long)numberOfPagesForPaginatorView:(SYPaginatorView *)arg1;
@end

