//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SYPaginatorViewDataSource.h"
#import "SYPaginatorViewDelegate.h"

@class NSString, SYPaginatorView;

@interface SYPaginatorViewController : UIViewController <SYPaginatorViewDataSource, SYPaginatorViewDelegate>
{
    SYPaginatorView *_paginator;
}

@property(readonly, nonatomic) SYPaginatorView *paginatorView; // @synthesize paginatorView=_paginator;
- (void).cxx_destruct;
- (id)paginatorView:(id)arg1 viewForPageAtIndex:(long long)arg2;
- (long long)numberOfPagesForPaginatorView:(id)arg1;
- (void)_initialize;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

