//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@interface SYPaginatorScrollView : UIScrollView
{
}

@property(nonatomic) id <UIScrollViewDelegate> privateDelegate;
- (void)setDelegate:(id)arg1;

@end

