//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSMutableDictionary, NSString, SYPageControl, UIScrollView;

@interface SYPaginatorView : UIView <UIScrollViewDelegate>
{
    NSMutableDictionary *_pages;
    NSMutableDictionary *_reuseablePages;
    _Bool _pageControlUsed;
    _Bool _pageSetViaPublicMethod;
    _Bool _isInfinite;
    int _paginationDirection;
    UIScrollView *_scrollView;
    SYPageControl *_pageControl;
    id <SYPaginatorViewDataSource> _dataSource;
    id <SYPaginatorViewDelegate> _delegate;
    double _pageGapWidth;
    long long _pagesToPreload;
    long long _currentPageIndex;
    struct CGRect _swipeableRect;
}

@property(nonatomic) _Bool isInfinite; // @synthesize isInfinite=_isInfinite;
@property(nonatomic) int paginationDirection; // @synthesize paginationDirection=_paginationDirection;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(nonatomic) struct CGRect swipeableRect; // @synthesize swipeableRect=_swipeableRect;
@property(nonatomic) long long numberOfPagesToPreload; // @synthesize numberOfPagesToPreload=_pagesToPreload;
@property(nonatomic) double pageGapWidth; // @synthesize pageGapWidth=_pageGapWidth;
@property(nonatomic) id <SYPaginatorViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) id <SYPaginatorViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) SYPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)scrollVisibleToCorrectView;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_setCurrentPageIndex:(long long)arg1 animated:(_Bool)arg2 scroll:(_Bool)arg3 forcePreload:(_Bool)arg4;
- (void)_reusePages;
- (void)_reuseViewAtIndex:(long long)arg1;
- (void)_removeViewAtIndex:(long long)arg1;
- (void)_cleanup;
- (void)_resetScrollViewContentSize;
- (double)_offsetForPage:(long long)arg1;
- (void)_loadPagesToPreloadAroundPageAtIndex:(long long)arg1;
- (void)_loadPage:(long long)arg1;
- (void)_pageControlChanged:(id)arg1;
- (id)currentPage;
- (id)dequeueReusablePageWithIdentifier:(id)arg1;
- (id)pageForIndex:(long long)arg1;
- (struct CGRect)frameForPageAtIndex:(long long)arg1;
- (void)setCurrentPageIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)reloadDataRemovingCurrentPage:(_Bool)arg1;
- (void)reloadData;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initializeWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
@property(readonly, nonatomic) long long numberOfPages;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

