//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QQApiInterfaceDelegate.h"
#import "TencentSessionDelegate.h"
#import "WXApiDelegate.h"

@class NSString;

@interface ThirdPartyManager : NSObject <WXApiDelegate, QQApiInterfaceDelegate, TencentSessionDelegate>
{
    CDUnknownBlockType _wxFinishBlock;
}

+ (id)sharedManager;
@property(copy, nonatomic) CDUnknownBlockType wxFinishBlock; // @synthesize wxFinishBlock=_wxFinishBlock;
- (void).cxx_destruct;
- (void)handleWechatCallback:(id)arg1;
- (void)requestWechatLogin:(CDUnknownBlockType)arg1;
- (_Bool)handleThirdPartyCallback:(id)arg1;
- (_Bool)checkThirdPartyCallback:(id)arg1;
- (void)setupThirdPartyCallback;
- (void)setupThirdPartyAuthorization;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

