//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage, UIImageView;

@interface TYMActivityIndicatorView : UIView
{
    _Bool _animating;
    _Bool _hidesWhenStopped;
    UIImage *_indicatorImage;
    UIImage *_backgroundImage;
    UIImageView *_indicatorImageView;
    UIImageView *_backgroundImageView;
    double _fullRotationDuration;
    double _progress;
    double _minProgressUnit;
    long long _activityIndicatorViewStyle;
}

@property(nonatomic) long long activityIndicatorViewStyle; // @synthesize activityIndicatorViewStyle=_activityIndicatorViewStyle;
@property(nonatomic) double minProgressUnit; // @synthesize minProgressUnit=_minProgressUnit;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) double fullRotationDuration; // @synthesize fullRotationDuration=_fullRotationDuration;
@property(nonatomic) _Bool hidesWhenStopped; // @synthesize hidesWhenStopped=_hidesWhenStopped;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UIImageView *indicatorImageView; // @synthesize indicatorImageView=_indicatorImageView;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIImage *indicatorImage; // @synthesize indicatorImage=_indicatorImage;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
- (void).cxx_destruct;
- (void)_rotateImageViewFrom:(double)arg1 to:(double)arg2 duration:(double)arg3 repeatCount:(double)arg4;
- (void)_initialize;
- (void)stopAnimating;
- (void)startAnimating;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithActivityIndicatorStyle:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isAnimating;

@end

