//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActionSheet.h"

#import "UI7Patch.h"

@class NSString;

@interface UI7ActionSheet : UIActionSheet <UI7Patch>
{
}

+ (void)patch;
+ (void)initialize;
- (void)showInView:(id)arg1;
- (void)showFromToolbar:(id)arg1;
- (void)showFromTabBar:(id)arg1;
- (void)showFromRect:(struct CGRect)arg1 inView:(id)arg2 animated:(_Bool)arg3;
- (void)showFromBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

