//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

#import "UI7Patch.h"

@class NSString;

@interface UI7Button : UIButton <UI7Patch>
{
}

+ (id)buttonWithType:(long long)arg1;
+ (void)patch;
+ (void)initialize;
- (void)___setTintColor:(id)arg1;
- (id)___tintColor;
- (void)setTitleColor:(id)arg1 forState:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)_UIRoundedRectButton_initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

