//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UI7Color : UIColor
{
}

+ (id)groupTableViewBackgroundColor;
+ (id)groupedTableViewSectionBackgroundColor;
+ (id)defaultTrackTintColor;
+ (id)defaultEmphasizedColor;
+ (id)defaultTintColor;
+ (id)defaultBackgroundColor;
+ (id)blackTabBarColor;
+ (id)blackBarColor;
+ (id)defaultBarColor;

@end

