//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UI7Patch.h"

@class NSString, UIColor;

@interface UI7Kit : NSObject <UI7Patch>
{
    UIColor *_tintColor;
    UIColor *_backgroundColor;
}

+ (void)patch;
+ (void)excludeClassNamesFromAutopatch:(id)arg1;
+ (void)initialize;
+ (id)kit;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

