//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationItem.h"

#import "UI7Patch.h"

@class NSString;

@interface UI7NavigationItem : UINavigationItem <UI7Patch>
{
}

+ (void)patch;
+ (void)initialize;
- (void)setRightBarButtonItems:(id)arg1 animated:(_Bool)arg2;
- (void)setLeftBarButtonItems:(id)arg1 animated:(_Bool)arg2;
- (void)setBackBarButtonItem:(id)arg1;
- (void)setRightBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (void)setLeftBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (id)initWithTitle:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

