//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NSCoding.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CALayer, NSMutableArray, NSString, UIColor, UIImageView;

@interface UI7PickerLikeView : UIView <NSCoding, UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate>
{
    UIColor *_textColor;
    UIColor *_selectionIndicatorColor;
    _Bool _showsSelectionIndicator;
    id <UIPickerViewDataSource> _dataSource;
    id <UIPickerViewDelegate> _delegate;
    NSMutableArray *_tables;
    UIView *_topFrame;
    NSMutableArray *_dividers;
    NSMutableArray *_selectionBars;
    UIView *_backgroundView;
    UIImageView *_topGradient;
    UIImageView *_bottomGradient;
    UIView *_foregroundView;
    CALayer *_maskGradientLayer;
    UIView *_topLineView;
    UIView *_bottomLineView;
}

+ (_Bool)isSubclassOfClass:(Class)arg1;
@property(retain, nonatomic) UIView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) UIView *topLineView; // @synthesize topLineView=_topLineView;
@property(retain, nonatomic) CALayer *maskGradientLayer; // @synthesize maskGradientLayer=_maskGradientLayer;
@property(retain, nonatomic) UIView *foregroundView; // @synthesize foregroundView=_foregroundView;
@property(retain, nonatomic) UIImageView *bottomGradient; // @synthesize bottomGradient=_bottomGradient;
@property(retain, nonatomic) UIImageView *topGradient; // @synthesize topGradient=_topGradient;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSMutableArray *selectionBars; // @synthesize selectionBars=_selectionBars;
@property(retain, nonatomic) NSMutableArray *dividers; // @synthesize dividers=_dividers;
@property(retain, nonatomic) UIView *topFrame; // @synthesize topFrame=_topFrame;
@property(retain, nonatomic) NSMutableArray *tables; // @synthesize tables=_tables;
@property(nonatomic) _Bool showsSelectionIndicator; // @synthesize showsSelectionIndicator=_showsSelectionIndicator;
@property(nonatomic) id <UIPickerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) id <UIPickerViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)selectedRowInComponent:(long long)arg1;
- (void)selectRow:(long long)arg1 inComponent:(long long)arg2 animated:(_Bool)arg3;
- (void)reloadComponent:(long long)arg1;
- (void)reloadAllComponents;
- (struct CGSize)rowSizeForComponent:(long long)arg1;
- (id)viewForRow:(long long)arg1 forComponent:(long long)arg2;
- (long long)numberOfRowsInComponent:(long long)arg1;
@property(readonly, nonatomic) long long numberOfComponents;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_backgroundColorUpdated;
- (void)_updateGradient;
- (void)_initPickerView;
- (_Bool)isKindOfClass:(Class)arg1;
@property(retain, nonatomic) UIColor *selectionIndicatorColor;
@property(retain, nonatomic) UIColor *textColor;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

