//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UI7Patch.h"

@class NSString;

@interface UI7TableViewCell : UITableViewCell <UI7Patch>
{
}

+ (void)patch;
+ (void)initialize;
- (long long)accessoryType;
- (void)setAccessoryType:(long long)arg1;
- (void)setAccessoryView:(id)arg1;
- (void)_setTableBackgroundCGColor:(struct CGColor *)arg1 withSystemColorName:(id)arg2;
- (void)setTableViewStyle:(int)arg1;
- (void)setBackgroundColor:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

