//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActionSheet.h"

@interface UIActionSheet (Patch)
- (void)_setTheme;
- (double)__tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)__tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)__showInView:(id)arg1;
- (void)__showFromToolbar:(id)arg1;
- (void)__showFromTabBar:(id)arg1;
- (void)__showFromRect:(struct CGRect)arg1 inView:(id)arg2 animated:(_Bool)arg3;
- (void)__showFromBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (id)__init;
- (id)init;
@end

