//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

@interface UIAlertView (Shortcuts)
+ (id)showNoticeWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3;
+ (id)showLog:(id)arg1 file:(char *)arg2 line:(int)arg3;
- (id)initNoticeWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3;
@end

