//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

@interface UIAlertView (Patch)
- (void)__dismissWithClickedButtonIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)__show;
- (id)__init;
- (id)init;
@end

