//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class UIImage;

@interface UIASegmentedImageView : UIImageView
{
    _Bool _autosizing;
    UIImageView *_centerImageView;
    UIImageView *_topImageView;
    UIImageView *_bottomImageView;
    UIImageView *_leftImageView;
    UIImageView *_rightImageView;
    UIImageView *_topLeftImageView;
    UIImageView *_topRightImageView;
    UIImageView *_bottomLeftImageView;
    UIImageView *_bottomRightImageView;
    UIImage *_centerImage;
    UIImage *_topImage;
    UIImage *_bottomImage;
    UIImage *_leftImage;
    UIImage *_rightImage;
    UIImage *_topLeftImage;
    UIImage *_topRightImage;
    UIImage *_bottomLeftImage;
    UIImage *_bottomRightImage;
    double _topMargin;
    double _bottomMargin;
    double _leftMargin;
    double _rightMargin;
}

@property(nonatomic) double rightMargin; // @synthesize rightMargin=_rightMargin;
@property(nonatomic) double leftMargin; // @synthesize leftMargin=_leftMargin;
@property(nonatomic) double bottomMargin; // @synthesize bottomMargin=_bottomMargin;
@property(nonatomic) double topMargin; // @synthesize topMargin=_topMargin;
@property(nonatomic) _Bool autosizing; // @synthesize autosizing=_autosizing;
@property(retain, nonatomic) UIImage *bottomRightImage; // @synthesize bottomRightImage=_bottomRightImage;
@property(retain, nonatomic) UIImage *bottomLeftImage; // @synthesize bottomLeftImage=_bottomLeftImage;
@property(retain, nonatomic) UIImage *topRightImage; // @synthesize topRightImage=_topRightImage;
@property(retain, nonatomic) UIImage *topLeftImage; // @synthesize topLeftImage=_topLeftImage;
@property(retain, nonatomic) UIImage *rightImage; // @synthesize rightImage=_rightImage;
@property(retain, nonatomic) UIImage *leftImage; // @synthesize leftImage=_leftImage;
@property(retain, nonatomic) UIImage *bottomImage; // @synthesize bottomImage=_bottomImage;
@property(retain, nonatomic) UIImage *topImage; // @synthesize topImage=_topImage;
@property(retain, nonatomic) UIImage *centerImage; // @synthesize centerImage=_centerImage;
@property(retain, nonatomic) UIImageView *bottomRightImageView; // @synthesize bottomRightImageView=_bottomRightImageView;
@property(retain, nonatomic) UIImageView *bottomLeftImageView; // @synthesize bottomLeftImageView=_bottomLeftImageView;
@property(retain, nonatomic) UIImageView *topRightImageView; // @synthesize topRightImageView=_topRightImageView;
@property(retain, nonatomic) UIImageView *topLeftImageView; // @synthesize topLeftImageView=_topLeftImageView;
@property(retain, nonatomic) UIImageView *rightImageView; // @synthesize rightImageView=_rightImageView;
@property(retain, nonatomic) UIImageView *leftImageView; // @synthesize leftImageView=_leftImageView;
@property(retain, nonatomic) UIImageView *bottomImageView; // @synthesize bottomImageView=_bottomImageView;
@property(retain, nonatomic) UIImageView *topImageView; // @synthesize topImageView=_topImageView;
@property(retain, nonatomic) UIImageView *centerImageView; // @synthesize centerImageView=_centerImageView;
- (void).cxx_destruct;
- (void)setImage:(id)arg1;
- (id)image;
- (void)arrange;
- (id)initWithLeftImage:(id)arg1 centerImage:(id)arg2 rightImage:(id)arg3;
- (id)initWithTopImage:(id)arg1 centerImage:(id)arg2 bottomImage:(id)arg3;
- (id)initWithCenterImage:(id)arg1 highlightedImage:(id)arg2;
- (id)initWithCenterImage:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)_segmentedImageViewInit;

@end

