//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIView<UIAViewLifeCycle>;

@interface UIAViewController : UIViewController
{
}

- (void)didReceiveMemoryWarning;
- (void)viewDidUnload;
- (void)viewWillUnload;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(retain, nonatomic) UIView<UIAViewLifeCycle> *view; // @dynamic view;

@end

