//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@interface UIBarButtonItem (Patch)
- (void)_barButtonItemInit;
- (void)_barButtonItemInitWithFont:(id)arg1;
- (id)_tintColor;
- (id)__tintColor;
- (id)__initWithTitle:(id)arg1 style:(long long)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)__initWithBarButtonSystemItem:(long long)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)__initWithImage:(id)arg1 style:(long long)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)__initWithCoder:(id)arg1;
@end

