//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBezierPath.h"

@interface UIBezierPath (UIImage)
- (id)imageWithFillColor:(id)arg1;
- (id)imageWithStrokeColor:(id)arg1;
- (id)imageWithStrokeColor:(id)arg1 fillColor:(id)arg2;
@end

