//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor;

@interface UIButton (Accessor)
@property(retain, nonatomic, setter=___setBackgroundColor:) UIColor *___backgroundColor;
@property(retain, nonatomic, setter=___setDisabledTextTitleColor:) UIColor *___disabledTextTitleColor;
@property(retain, nonatomic, setter=___setSelectedTextTitleColor:) UIColor *___selectedTextTitleColor;
@property(retain, nonatomic, setter=___setHighLightedTextTitleColor:) UIColor *___highLightedTextTitleColor;
@property(retain, nonatomic, setter=___setTextTitleColor:) UIColor *___textTitleColor;
@end

