//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface UIButton (Patch)
+ (id)__buttonWithType:(long long)arg1;
- (void)_tintColorUpdated;
- (void)_buttonInitTheme;
- (void)__setTintColor:(id)arg1;
- (id)__tintColor;
- (void)__setBackgroundColor:(id)arg1;
- (void)__setTitleColor:(id)arg1 forState:(unsigned long long)arg2;
- (id)__initWithFrame:(struct CGRect)arg1;
- (id)__initWithCoder:(id)arg1;
@end

