//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (HTMLColorInternal)
+ (id)colorWithHTMLHexExpression32a:(id)arg1;
+ (id)colorWithHTMLHexExpression16a:(id)arg1;
+ (id)colorWithHTMLHexExpression32:(id)arg1;
+ (id)colorWithHTMLHexExpression16:(id)arg1;
+ (id)colorWithHTMLColorName:(id)arg1;
+ (void)initialize;
- (id)initWithHTMLHexExpression32a:(id)arg1;
- (id)initWithHTMLHexExpression16a:(id)arg1;
- (id)initWithHTMLHexExpression32:(id)arg1;
- (id)initWithHTMLHexExpression16:(id)arg1;
@end

