//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@class UIAColorComponents;

@interface UIColor (Shortcuts)
@property(readonly, nonatomic) int CGColorSpaceModel;
@property(readonly, nonatomic) struct CGColorSpace *CGColorSpace;
@property(readonly, nonatomic) UIAColorComponents *components;
@end

