//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (Creations)
+ (id)colorWith32bitColor:(unsigned int)arg1;
+ (id)colorWith8bitWhite:(unsigned char)arg1 alpha:(unsigned char)arg2;
+ (id)colorWith8bitRed:(unsigned char)arg1 green:(unsigned char)arg2 blue:(unsigned char)arg3 alpha:(unsigned char)arg4;
- (id)initWith32bitColor:(unsigned int)arg1;
- (id)initWith8bitWhite:(unsigned char)arg1 alpha:(unsigned char)arg2;
- (id)initWith8bitRed:(unsigned char)arg1 green:(unsigned char)arg2 blue:(unsigned char)arg3 alpha:(unsigned char)arg4;
@end

