//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (iOS7)
@property(readonly, nonatomic) _Bool needsUI7Kit;
@property(readonly, nonatomic, getter=isIOS7) _Bool iOS7;
@property(readonly, nonatomic) long long majorVersion;
@end

