//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (UI7Kit)
+ (id)iOS7SystemFontOfSize:(double)arg1 weight:(id)arg2;
+ (id)iOS7SystemFontOfSize:(double)arg1;
+ (id)iOS7SystemFontOfSize:(double)arg1 attribute:(id)arg2;
@end

