//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (ScaleImage)
- (id)imageByScalingAndCroppingForSize:(struct CGSize)arg1;
- (id)generatePhotoThumbnailWithSize:(struct CGSize)arg1;
- (id)compressImageWithPointSize:(struct CGSize)arg1;
- (id)compressImageWithPixelSize:(struct CGSize)arg1;
- (id)scaleToSize:(struct CGSize)arg1;
- (id)scaleToSizeUseUIGraphics:(struct CGSize)arg1;
@end

