//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImagePickerController.h"

@interface UIImagePickerController (Expansion)
+ (_Bool)cameraSupportsMedia:(id)arg1 sourceType:(long long)arg2;
+ (_Bool)canUserPickPhotosFromPhotoLibrary;
+ (_Bool)canUserPickVideosFromPhotoLibrary;
+ (_Bool)isPhotoLibraryAvailable;
+ (_Bool)doesCameraSupportTakingPhotos;
+ (_Bool)isFrontCameraAvailable;
+ (_Bool)isRearCameraAvailable;
+ (_Bool)isCameraAvailable;
@end

