//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (UIGraphics)
+ (id)imageWithBezierPath:(id)arg1 color:(id)arg2 backgroundColor:(id)arg3;
+ (id)clearImage;
+ (id)imageWithColor:(id)arg1 size:(struct CGSize)arg2;
- (id)imageByFilledWithColor:(id)arg1;
- (id)imageByCroppedToRect:(struct CGRect)arg1;
- (id)imageByResizingToSize:(struct CGSize)arg1;
@end

