//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (WebImage)
- (id)urlWith:(id)arg1 imageType:(long long)arg2;
- (void)setImageByUrl:(id)arg1 withType:(long long)arg2 defImageObj:(id)arg3 errorImageObj:(id)arg4;
- (void)setImageByUrl:(id)arg1 withType:(long long)arg2 defImage:(id)arg3 errorImage:(id)arg4;
@end

