//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Creations)
+ (id)imageWithContentsOfURL:(id)arg1 cachePolicy:(unsigned long long)arg2;
+ (id)imageWithContentsOfURLRequest:(id)arg1;
+ (id)imageWithContentsOfURL:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1 cachePolicy:(unsigned long long)arg2;
- (id)initWithContentsOfURLRequest:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
@end

