//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Utility)
+ (id)imageWithStartColor:(id)arg1 endColor:(id)arg2 size:(struct CGSize)arg3;
- (id)fixOrientation;
- (id)addImage:(id)arg1 edgeInsets:(struct UIEdgeInsets)arg2;
- (id)generatePhotoThumbnailWithSize:(struct CGSize)arg1;
- (id)compressImageWithPointSize:(struct CGSize)arg1;
- (id)compressImageWithPixelSize:(struct CGSize)arg1;
@end

