//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationBar.h"

@interface UINavigationBar (Patch)
- (void)_tintColorUpdated;
- (void)_navigationBarInit;
- (void)__setTintColor:(id)arg1;
- (id)__tintColor;
- (void)__pushNavigationItem:(id)arg1;
- (void)__setBarStyle:(long long)arg1;
- (id)__initWithFrame:(struct CGRect)arg1;
- (id)__initWithCoder:(id)arg1;
- (id)__init;
- (id)init;
@end

