//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationItem.h"

@interface UINavigationItem (Patch)
- (void)__setRightBarButtonItems:(id)arg1 animated:(_Bool)arg2;
- (void)__setLeftBarButtonItems:(id)arg1 animated:(_Bool)arg2;
- (void)__setBackBarButtonItem:(id)arg1;
- (void)__setRightBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (void)__setLeftBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (id)__initWithTitle:(id)arg1;
- (id)__initWithCoder:(id)arg1;
- (id)__init;
@end

