//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface UINavigationController (Patch)
- (void)_navigationControllerInit;
- (id)__initWithRootViewController:(id)arg1;
- (id)__initWithCoder:(id)arg1;
- (id)__init;
@end

