//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPickerView.h"

@class NSArray, UIImageView, UIView;

@interface UIPickerView (Accessor)
@property(readonly, nonatomic) UIImageView *bottomGradient;
@property(readonly, nonatomic) UIImageView *topGradient;
@property(readonly, nonatomic) NSArray *tables;
@property(retain, nonatomic) UIView *backgroundView;
@end

