//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIProgressView.h"

@interface UIProgressView (Patch)
- (void)_tintColorUpdated;
- (void)_progressTintColorUpdated;
- (void)_trackTintColorUpdated;
- (void)_progressViewInit;
- (id)__progressTintColor;
- (id)__trackTintColor;
- (id)__initWithProgressViewStyle:(long long)arg1;
- (id)__initWithCoder:(id)arg1;
- (id)__initWithFrame:(struct CGRect)arg1;
@end

