//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISearchBar.h"

@interface UISearchBar (Patch)
- (void)_searchBarInit;
- (id)__initWithFrame:(struct CGRect)arg1;
- (id)__initWithCoder:(id)arg1;
@end

