//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISegmentedControl.h"

@interface UISegmentedControl (Patch)
- (void)_backgroundColorUpdated;
- (void)_tintColorUpdated;
- (struct CGSize)intrinsicContentSize;
- (void)_segmentedControlInit;
- (void)__setFrame:(struct CGRect)arg1;
- (void)__setTintColor:(id)arg1;
- (id)__tintColor;
- (void)__awakeFromNib;
- (id)__initWithCoder:(id)arg1;
- (id)__initWithFrame:(struct CGRect)arg1;
- (id)__initWithItems:(id)arg1;
- (void)awakeFromNib;
@end

