//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISlider.h"

@interface UISlider (Patch)
- (void)_tintColorUpdated;
- (void)_sliderInit;
- (void)_maximumTrackTintColorUpdated;
- (void)_minimumTrackTintColorUpdated;
- (id)__maximumTrackTintColor;
- (id)__minimumTrackTintColor;
- (id)__initWithCoder:(id)arg1;
- (id)__initWithFrame:(struct CGRect)arg1;
@end

