//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIStepper.h"

@interface UIStepper (Patch)
- (void)_tintColorUpdated;
- (void)_stepperInit;
- (void)__setTintColor:(id)arg1;
- (id)__tintColor;
- (void)__awakeFromNib;
- (id)__init;
- (void)awakeFromNib;
@end

