//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBar.h"

@interface UITabBar (UI7Kit)
- (void)_tintColorUpdated;
- (void)_setBarStyle:(long long)arg1;
- (long long)_barStyle;
@end

