//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@interface UITableViewCell (Patch)
- (void)_tintColorUpdated;
- (id)_tintColor;
- (void)_accessoryButtonTapped:(id)arg1;
- (void)_tableViewCellInit;
- (void)__setTableViewStyle:(int)arg1;
- (void)__setBackgroundColor:(id)arg1;
- (void)__setAccessoryView:(id)arg1;
- (void)__setAccessoryType:(long long)arg1;
- (long long)__accessoryType;
- (id)__tintColor;
- (id)__initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)__initWithCoder:(id)arg1;
@end

