//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarItem.h"

@interface UITabBarItem (Patch)
+ (void)initialize;
- (void)_tabBarItemInit;
- (id)__updateImageWithTintColor:(id)arg1 isSelected:(_Bool)arg2 getImageOffset:(struct UIOffset *)arg3;
- (id)__initWithTabBarSystemItem:(long long)arg1 tag:(long long)arg2;
- (id)__initWithCoder:(id)arg1;
@end

