//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@interface UITableView (Patch)
- (id)__dequeueReusableCellWithIdentifier:(id)arg1 forIndexPath:(id)arg2;
- (void)awakeFromNib;
- (void)_tableViewInitGrouped;
- (void)_tableViewInit;
- (void)__updateVisibleCellsNow:(_Bool)arg1;
- (long long)__style;
- (void)__setDataSource:(id)arg1;
- (void)__setDelegate:(id)arg1;
- (id)__initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
- (id)__initWithFrame:(struct CGRect)arg1;
- (id)__initWithCoder:(id)arg1;
@end

