//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSIndexPath, UITableView;

@interface UITableViewCell (Shortcuts)
+ (id)cellWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(readonly, nonatomic) NSIndexPath *indexPath;
@property(readonly, nonatomic) UITableView *tableView;
- (void)setReuseIdentifier:(id)arg1;
@end

