//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@interface UITextField (Patch)
- (void)_textFieldInit;
- (struct CGRect)__editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)__textRectForBounds:(struct CGRect)arg1;
- (void)__setBorderStyle:(long long)arg1;
- (long long)__borderStyle;
- (id)__initWithFrame:(struct CGRect)arg1;
- (id)__initWithCoder:(id)arg1;
@end

