//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (ShowDot)
- (void)hideDotWithBadge:(id)arg1;
- (void)showDotWithOffset:(struct CGPoint)arg1 withBoardLine:(_Bool)arg2 withBadge:(id)arg3;
- (void)showDotWithOffset:(struct CGPoint)arg1 withBadge:(id)arg2;
@end

