//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MONActivityIndicatorViewDelegate.h"

@class NSString, UIButton;

@interface UIView (JTLoadingView) <MONActivityIndicatorViewDelegate>
- (id)imageByFilledWithColor:(id)arg1 image:(id)arg2;
- (id)activityIndicatorView:(id)arg1 circleBackgroundColorAtIndex:(unsigned long long)arg2;
- (void)resetActivityPositions;
- (_Bool)isActivityAnimating;
- (void)stopActivityAnimation;
- (void)startActivityAnimationWithType:(unsigned long long)arg1 atPositon:(struct CGPoint)arg2 autoResize:(_Bool)arg3;
- (void)startActivityAnimationWithType:(unsigned long long)arg1 atPositon:(struct CGPoint)arg2;
- (void)startActivityAnimationWithType:(unsigned long long)arg1;
- (void)startActivityAnimation;
- (void)hideIndicatorText;
- (void)showIndicatorTextWith:(id)arg1 clickBlock:(CDUnknownBlockType)arg2;
- (void)_actionIndicatorTextClick:(id)arg1;
- (void)showIndicatorTextWith:(id)arg1;
@property(nonatomic) double indicatorPoistionY; // @dynamic indicatorPoistionY;
@property(readonly, nonatomic) UIButton *indicatorTextButton; // @dynamic indicatorTextButton;
- (void)setActivityIndicatorView:(id)arg1;
@property(readonly, nonatomic) UIView *activityIndicatorView; // @dynamic activityIndicatorView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

