//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface UIView (CALayerShortcut)
@property double shadowRadius;
@property struct CGSize shadowOffset;
@property(retain) UIColor *shadowColor;
@property float shadowAlpha;
@property double cornerRadius;
@property double borderWidth;
@property(copy) UIColor *borderColor;
@end

