//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (DefaultEmptyView)
- (void)actionDefaultEmptyViewTaped:(id)arg1;
- (_Bool)isShowDefaultEmptyView;
- (void)hideDefaultEmptyView;
- (void)showEmptyViewWithImageName:(id)arg1 text:(id)arg2 textColor:(id)arg3 centerOffset:(double)arg4 tapBlock:(CDUnknownBlockType)arg5;
- (void)showEmptyViewWithImageName:(id)arg1 text:(id)arg2 centerOffset:(double)arg3 tapBlock:(CDUnknownBlockType)arg4;
- (void)showImageEmptyViewWithImageName:(id)arg1 text:(id)arg2 centerOffset:(double)arg3 tapBlock:(CDUnknownBlockType)arg4;
- (void)showImageEmptyViewWithImageName:(id)arg1 text:(id)arg2 tapBlock:(CDUnknownBlockType)arg3;
- (void)showImageEmptyViewWithImageName:(id)arg1 text:(id)arg2;
- (void)showDefaultEmptyViewWithText:(id)arg1 centerOffset:(double)arg2 tapBlock:(CDUnknownBlockType)arg3;
- (void)showDefaultEmptyViewWithText:(id)arg1 tapBlock:(CDUnknownBlockType)arg2;
- (void)showDefaultEmptyViewWithText:(id)arg1;
@end

