//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (UI7View)
+ (void)initialize;
- (void)_didMoveToWindow;
- (void)_didMoveToSuperview;
- (id)stackedBackgroundColor;
- (void)_backgroundColorUpdated;
- (void)_tintColorUpdated;
- (void)_setTintColor:(id)arg1;
- (id)_tintColor;
- (void)_view_setTintColor:(id)arg1;
- (id)_view_tintColor;
- (void)_current_setTintColor:(id)arg1;
- (id)_current_tintColor;
@end

