//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Layer)
- (id)snapshotWithEdgeInsets:(struct UIEdgeInsets)arg1;
- (void)_layoutBorderLineForDirection:(unsigned long long)arg1;
- (id)_borderLineColorTupleForDirection:(unsigned long long)arg1;
- (void)_resetBorderLineInset:(struct UIEdgeInsets)arg1 forDirection:(unsigned long long)arg2 withMask:(unsigned long long)arg3;
- (void)_resetBorderLineColor:(id)arg1 forDirection:(unsigned long long)arg2 withMask:(unsigned long long)arg3;
- (void)_resetBorderLineForDirection:(unsigned long long)arg1 withMask:(unsigned long long)arg2;
- (void)layoutBorderLineIfNeeded;
- (id)borderLineColorForDirection:(unsigned long long)arg1;
- (void)setBorderLineColor:(id)arg1 forDirectionMask:(unsigned long long)arg2;
- (void)setBorderLineInsets:(struct UIEdgeInsets)arg1 forDirectionMask:(unsigned long long)arg2;
- (void)setBorderLineInsets:(struct UIEdgeInsets)arg1;
- (void)showBorderLineWithDirectionMask:(unsigned long long)arg1;
- (void)makeCornerRadius:(double)arg1;
@end

