//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSArray, NSString;

@interface UploadFileOp : BaseOp
{
    NSString *_req_fileExtType;
    NSString *_req_uploadUrl;
    NSArray *_req_fileDataArray;
    NSArray *_rsp_urlArray;
    NSArray *_rsp_idArray;
    NSString *_rsp_tip;
    NSArray *_fileArray;
    CDUnknownBlockType _fileDataBlock;
    CDUnknownBlockType _progressBlock;
}

@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(copy, nonatomic) CDUnknownBlockType fileDataBlock; // @synthesize fileDataBlock=_fileDataBlock;
@property(retain, nonatomic) NSArray *fileArray; // @synthesize fileArray=_fileArray;
@property(retain, nonatomic) NSString *rsp_tip; // @synthesize rsp_tip=_rsp_tip;
@property(retain, nonatomic) NSArray *rsp_idArray; // @synthesize rsp_idArray=_rsp_idArray;
@property(retain, nonatomic) NSArray *rsp_urlArray; // @synthesize rsp_urlArray=_rsp_urlArray;
@property(retain, nonatomic) NSArray *req_fileDataArray; // @synthesize req_fileDataArray=_req_fileDataArray;
@property(retain, nonatomic) NSString *req_uploadUrl; // @synthesize req_uploadUrl=_req_uploadUrl;
@property(retain, nonatomic) NSString *req_fileExtType; // @synthesize req_fileExtType=_req_fileExtType;
- (void).cxx_destruct;
- (void)setProgress:(CDUnknownBlockType)arg1;
- (void)setFileArray:(id)arg1 withGetDataBlock:(CDUnknownBlockType)arg2;
- (id)rac_postRequest;

@end

