//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOp.h"

@class NSString;

@interface UserBankAuthInfoOp : BaseOp
{
    NSString *_rsp_phone;
    NSString *_rsp_name;
    NSString *_rsp_bankCardNo;
    NSString *_rsp_idNo;
}

@property(retain, nonatomic) NSString *rsp_idNo; // @synthesize rsp_idNo=_rsp_idNo;
@property(retain, nonatomic) NSString *rsp_bankCardNo; // @synthesize rsp_bankCardNo=_rsp_bankCardNo;
@property(retain, nonatomic) NSString *rsp_name; // @synthesize rsp_name=_rsp_name;
@property(retain, nonatomic) NSString *rsp_phone; // @synthesize rsp_phone=_rsp_phone;
- (void).cxx_destruct;
- (id)description;
- (id)parseResponseObject:(id)arg1;
- (id)rac_postRequest;

@end

