//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CheckVersionOp;

@interface VersionCheckHelper : NSObject
{
    CheckVersionOp *_versionCheckOp;
}

@property(retain, nonatomic) CheckVersionOp *versionCheckOp; // @synthesize versionCheckOp=_versionCheckOp;
- (void).cxx_destruct;
- (void)startUpdatingWithURLString:(id)arg1;
- (void)checkVersion;

@end

