//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel, UIWindow, ZYShareSheetView;

@interface ZYShareView : UIView
{
    ZYShareSheetView *_shareSheetView;
    UIView *_dimBackgroundView;
    UIWindow *_window;
}

+ (id)shareViewWithShareItems:(id)arg1 functionItems:(id)arg2;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) UIView *dimBackgroundView; // @synthesize dimBackgroundView=_dimBackgroundView;
@property(retain, nonatomic) ZYShareSheetView *shareSheetView; // @synthesize shareSheetView=_shareSheetView;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIButton *cancelButton;
@property(readonly, nonatomic) UILabel *titleLabel;
- (void)hideAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)showAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)removeFromKeyWindow;
- (void)addToKeyWindow;
- (void)hide;
- (void)show;
- (void)dealloc;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithItemsArray:(id)arg1;
- (id)initWithShareItems:(id)arg1 functionItems:(id)arg2;

@end

