//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UITextView, ZYShareItem;

@interface ZYShareItemCell : UICollectionViewCell
{
    ZYShareItem *_item;
    UIButton *_iconView;
    UITextView *_titleView;
}

@property(retain, nonatomic) UITextView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIButton *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) ZYShareItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)iconClick;
- (void)layoutSubviews;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

